# Fetching Data using Web Scraping

In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [4]:
requests.get("https://www.mul.edu.pk/en/programs/bs-programs")

In [6]:
webpage = requests.get("https://www.mul.edu.pk/en/programs/bs-programs").text

In [68]:
webpage

'  \n<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="utf-8">\n    <meta http-equiv="x-ua-compatible" content="ie=edge">\n    <meta name="robots" content="index, follow" />\n    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">\n    <link href="https://www.mul.edu.pk/images/favicon.ico" rel="shortcut icon" type="image/png">\n    <title>All Programs - Minhaj University Lahore</title>\n    <link rel="image_src" href="https://www.mul.edu.pk/images/minhaj-university-lahore.png">\n    <meta property="og:image:url" content="https://www.mul.edu.pk/images/minhaj-university-lahore.png">\n    <meta property="og:title" content="All Programs - Minhaj University Lahore">\n    <meta property="og:description" content="Graduate Program Post Graduate Program Diploma Computer Science Information Technology Associate Degree Commerce Software Engineering Political English Urdu Physics Mathematics Chemistry International Relations Mass Communication Pakistan Studies Medical Laboratory Technology Botany Zoology Economics Accounting Finance Food">\n    <meta property="og:url" content="https://www.mul.edu.pk/en/programs">\n    <meta property="og:site_name" content="Minhaj University Lahore">\n    <meta property="og:type" content="article">\n    <meta property="og:locale" content="en_US">\n    <meta property="article:author" content="https://www.facebook.com/MinhajUniversityLahore">\n    <meta property="article:publisher" content="https://www.facebook.com/MinhajUniversityLahore">\n    <meta name="twitter:card" content="summary">\n    <meta name="twitter:url" content="https://www.mul.edu.pk/en/programs">\n    <meta name="twitter:title" content="All Programs - Minhaj University Lahore">\n    <meta name="twitter:description" content="All Programs - Minhaj University Lahore">\n    <meta name="twitter:image:src" content="https://www.mul.edu.pk/images/minhaj-university-lahore.png">\n    <meta name="twitter:image" content="https://www.mul.edu.pk/images/minhaj-university-lahore.png">\n    <meta name="twitter:domain" content="Minhaj University Lahore">\n    <meta name="twitter:site" content="@OfficialMUL">\n    <meta name="twitter:creator" content="@OfficialMUL">\n    <meta itemprop="name" content="All Programs - Minhaj University Lahore">\n    <meta itemprop="description" content="Graduate Program Post Graduate Program Diploma Computer Science Information Technology Associate Degree Commerce Software Engineering Political English Urdu Physics Mathematics Chemistry International Relations Mass Communication Pakistan Studies Medical Laboratory Technology Botany Zoology Economics Accounting Finance Food">\n    <meta itemprop="image" content="https://www.mul.edu.pk/images/minhaj-university-lahore.png">\n    <meta itemprop="alternativeHeadline" content="All Programs - Minhaj University Lahore">\n    <meta itemprop="thumbnailUrl" content="https://www.mul.edu.pk/images/minhaj-university-lahore.png">\n    <meta name="description" content="Graduate Program Post Graduate Program Diploma Computer Science Information Technology Associate Degree Commerce Software Engineering Political English Urdu Physics Mathematics Chemistry International Relations Mass Communication Pakistan Studies Medical Laboratory Technology Botany Zoology Economics Accounting Finance Food">\n    <meta name="keywords" content="Graduate, Program, Post, Graduate, Program, Diploma, Computer, Science, Information, Technology, Associate, Degree, Commerce, Software, Engineering, Political, English, Urdu, Physics, Mathematics, Chemistry, International, Relations, Mass, Communication, Pakistan, Studies, Medical, Laboratory, Technology, Botany, Zoology, Economics, Accounting, Finance, Food">\n    <meta name="facebook-domain-verification" content="n43oiqg2dly4sr5bgy4nbuy9md1t7e" />\n\n    <link rel="stylesheet" href="https://www.mul.edu.pk/assets/css/vendor/bootstrap.min.css">\n    <link rel="stylesheet" href="https://www.mul.edu.pk/assets/css/vendor/slick.css">\n    <link rel="stylesheet" href="https://www.mul.edu.pk/assets/css/vendor/slick-theme.css">\n    <link rel="stylesheet" href="https://www.mul.edu.pk/assets/css/plugins/sal.css">\n    <link rel="stylesheet" href="https://www.mul.edu.pk/assets/css/plugins/feather.css">\n    <link rel="stylesheet" href="https://www.mul.edu.pk/assets/css/plugins/fontawesome.min.css">\n    <link rel="stylesheet" href="https://www.mul.edu.pk/assets/css/plugins/euclid-circulara.css">\n    <link rel="stylesheet" href="https://www.mul.edu.pk/assets/css/plugins/swiper.css">\n    <link rel="stylesheet" href="https://www.mul.edu.pk/assets/css/plugins/magnify.css">\n    <link rel="stylesheet" href="https://www.mul.edu.pk/assets/css/plugins/odometer.css">\n    <link rel="stylesheet" href="https://www.mul.edu.pk/assets/css/plugins/animation.css">\n    <link rel="stylesheet" href="https://www.mul.edu.pk/assets/css/plugins/bootstrap-select.min.css">\n    <link rel="stylesheet" href="https://www.mul.edu.pk/assets/css/plugins/jquery-ui.css">\n    <link rel="stylesheet" href="https://www.mul.edu.pk/assets/css/plugins/magnigy-popup.min.css">\n    <link rel="stylesheet" href="https://www.mul.edu.pk/assets/css/style.css">\n\n    <link href="https://www.mul.edu.pk/assets/zenfy/assets/css/bootstrap-icons.css" rel="stylesheet">\n    <link href="https://www.mul.edu.pk/assets/zenfy/assets/css/animate.min.css" rel="stylesheet">\n    <link href="https://www.mul.edu.pk/assets/zenfy/assets/css/jquery.fancybox.min.css" rel="stylesheet">\n    <link rel="stylesheet" href="https://www.mul.edu.pk/assets/zenfy/assets/css/swiper-bundle.min.css">\n    <link href="https://www.mul.edu.pk/assets/zenfy/assets/css/boxicons.min.css" rel="stylesheet">\n    <link rel="stylesheet" href="https://www.mul.edu.pk/assets/zenfy/assets/css/style.css">\n\n    <script>\n\t\t(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':\n\t\tnew Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],\n\t\tj=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\n\t\t\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);\n\t\t})(window,document,\'script\',\'dataLayer\',\'GTM-N72MWHD\');\n\t</script>\n\n    <meta name="google-site-verification" content="Dr_EKInP8uQ1Hq4inIju8l5qPoWrXMFghNnXBSzAJXY"/>\n    <script>\n\t\t(function(d, s, id) {\n\t\t\tvar js, fjs = d.getElementsByTagName(s)[0];\n\t\t\tif (d.getElementById(id)) return;\n\t\t\tjs = d.createElement(s); js.id = id;\n\t\t\tjs.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3&appId=473691367168921";\n\t\t\tfjs.parentNode.insertBefore(js, fjs);\n\t\t}(document, "script", "facebook-jssdk"));\n    </script>    <script>\n        !function(f,b,e,v,n,t,s)\n        {if(f.fbq)return;n=f.fbq=function(){n.callMethod?\n        n.callMethod.apply(n,arguments):n.queue.push(arguments)};\n        if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version=\'2.0\';\n        n.queue=[];t=b.createElement(e);t.async=!0;\n        t.src=v;s=b.getElementsByTagName(e)[0];\n        s.parentNode.insertBefore(t,s)}(window, document,\'script\',\n        \'https://connect.facebook.net/en_US/fbevents.js\');\n        fbq(\'init\', \'432949847984852\');\n        fbq(\'track\', \'PageView\');\n    </script>\n    <noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=432949847984852&ev=PageView&noscript=1"/></noscript>\n    \n</head>\n\n<style>\n    #nav {\n        transition: all 0.1s ease-in-out;\n    }\n</style>\n\n<body>\n\t<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-N72MWHD" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>\n    <div class="sidebar-menu">\n        <div class="sidebar-menu-top-area">\n            <div class="container d-flex align-items-center justify-content-between">\n                <div class="sidebar-menu-logo">\n                    <a href="https://www.mul.edu.pk/en/" class="logo-dark">\n                        <img alt="mul-logo" class="img-fluid" src="https://www.mul.edu.pk/images/mul_logo.jpg" style="width: 170px;">\n                    </a>\n                    <a href="https://www.mul.edu.pk/en/" class="logo-light">\n                        <img alt="mul-logo" class="img-fluid" src="https://www.mul.edu.pk/images/mul_logo.jpg" style="width: 170px;">\n                    </a>\n                </div>\n                <div class="sidebar-menu-close">\n                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 18 18">\n                        <path fill-rule="evenodd" clip-rule="evenodd"\n                            d="M18 0L11.1686 8.99601L18 18L9.0041 11.1605L0 18L6.83156 8.99601L0 0L9.0041 6.83156L18 0Z">\n                        </path>\n                    </svg>\n                </div>\n            </div>\n        </div>\n\n        <style>\n            .main-nav-element {\n                display: none;\n            }\n            @media Screen and (max-width: 990px) {\n                .main-nav-element {\n                    display: block;\n                }\n            }\n        </style>\n\n        <div class="container">\n            <div class="row g-lg-4 gy-5">\n                <div class="col-lg-8">\n                    <div class="sidebar-menu-wrap">\n                        <ul class="main-menu">\n                            <li class="main-nav-element">\n                                <a href="https://www.mul.edu.pk/en/">Home</a>\n                            </li>\n\n                            <li class="main-nav-element">\n                                <a href="#">About </a>\n                                <span class="dropdown-icon2"><i class="bi bi-plus"></i></span>\n                                <ul class="submenu-list">\n                                    <li> \n                                        <a href="#"> Leadership & <br> Governance</a>\n                                        <span style="position: absolute !important; top: 0;" class="dropdown-icon2"><i class="bi bi-plus"></i></span>\n                                        <ul class="submenu-list">\n\n                                            <li>\n                                                <a href="https://www.mul.edu.pk/en/welcome-message/welcome-from-the-chairman-board-of-governors-bog"> Chairman</a>\n                                            </li>\n                                            <li>\n                                                <a href="https://www.mul.edu.pk/en/welcome-message/message-from-the-deputy-chairman-bog"> Deputy Chairman</a>\n                                            </li>\n                                            <li> \n                                                <a href="https://www.mul.edu.pk/en/welcome-message/message-from-the-vice-chancellor"> Vice Chancellor</a>\n                                            </li>\n                                            <li> \n                                                <a href="https://www.mul.edu.pk/en/deans"> Deans</a>\n                                            </li>\n                                            <li> \n                                                <a href="https://www.mul.edu.pk/en/directors"> Directors</a>\n                                            </li>\n                                            <li> \n                                                <a href="https://www.mul.edu.pk/en/hods"> Head of Schools</a>\n                                            </li>\n                                            <li> \n                                                <a href="https://www.mul.edu.pk/en/bogs"> Board of Governors</a>\n                                            </li>\n                                            <li>\n                                                <a href="https://www.mul.edu.pk/en/academic-council"> Academic Council</a>\n                                            </li>\n                                            <li> \n                                                <a href="#"> Officers of MUL</a>\n                                                <span style="position: absolute !important; top: 0;" class="dropdown-icon2"><i class="bi bi-plus"></i></span>\n                                                <ul class="submenu-list">\n                                                    <!--<li>\n                                                        <a href="#"> Office of the Vice Chancellor</a>\n                                                    </li> -->\n                                                    <li>\n                                                        <a href="https://www.mul.edu.pk/en/office-of-registrar"> Office of the Registrar</a>\n                                                    </li>\n                                                    <!--<li>\n                                                        <a href="#"> Office of the Treasurer</a>\n                                                    </li>\n                                                    <li>\n                                                        <a href="#"> Office of Controller of Examination</a>\n                                                    </li> -->\n                                                </ul>\n                                            </li>\n\n                                        </ul>\n\n                                    </li>\n                                    <li> <a href="https://www.mul.edu.pk/en/about"> About MUL</a> </li>\n                                    <li> <a href="https://www.mul.edu.pk/en/mul-at-glance"> MUL at a Glance</a> </li>\n                                    <li> <a href="https://dgl.mul.edu.pk/" target="_blank"> Global Linkages</a> </li>\n                                </ul>\n                            </li>\n\n                            <li class="main-nav-element">\n                                <a href="https://www.mul.edu.pk/en/news-events">News & Events</a>\n                            </li>\n\n                            <li class="main-nav-element">\n                                <a href="#">Admissions </a>\n                                <span class="dropdown-icon2 active"><i class="bi bi-plus"></i></span>\n                                <ul class="submenu-list active">\n                                    <li> <a href="https://www.mul.edu.pk/en/programs"> All Programs</a></li>\n                                    <li> <a href="https://www.mul.edu.pk/en/programs/bs-programs"> BS Programs</a></li>\n                                    <li> <a href="https://www.mul.edu.pk/en/programs/mphil-programs"> M.Phil Programs</a></li>\n                                    <li> <a href="https://www.mul.edu.pk/en/programs/phd-programs"> Ph.D. Programs</a></li>\n                                    <li> <a href="https://www.mul.edu.pk/en/fee-calculator"> Fee Calculator</a></li>\n                                    <li> <a href="https://www.mul.edu.pk/en/scholarships-and-fee-concession"> Financial Aids & Scholarships</a></li>\n                                    <li> <a href="https://www.mul.edu.pk/en/admission-guide"> Admission Guide</a></li>\n                                    <li> <a href="https://www.mul.edu.pk/en/admission-policy"> Admission Policy</a></li>\n                                    <li> <a href="https://www.mul.edu.pk/downloads/MUL_Prospectus.pdf"> Prospectus</a></li>\n                                    <li> <a href="https://admission.mul.edu.pk/"> Apply Now</a></li>\n                                </ul>\n                            </li>\n\n                            <li class="main-nav-element">\n                                <a href="https://www.mul.edu.pk/en/contact">Contact</a>\n                            </li>\n\n                            <li>\n                                <a href="#">Academics </a>\n                                <span class="dropdown-icon2 active"><i class="bi bi-plus"></i></span>\n                                <ul class="submenu-list active">\n                                    <li>\n                                        <a href="#"> Faculties</a>\n                                        <span style="position: absolute !important; top: 0;" class="dropdown-icon2"><i class="bi bi-plus"></i></span>\n                                        <ul class="submenu-list">\n                                            <li> \n                                                <a href="https://www.mul.edu.pk/en/faculty/health-sciences"> Faculty of Allied Health Sciences</a> \n                                            </li>\n                                            <li> \n                                                <a href="https://www.mul.edu.pk/en/faculty/applied-sciences"> Faculty of Applied Sciences</a>\n                                            </li>\n                                            <li> \n                                                <a href="https://www.mul.edu.pk/en/faculty/art-designing-and-architecture"> Faculty of Art, Designing, & Architecture</a> \n                                            </li>\n                                            <li> \n                                                <a href="https://www.mul.edu.pk/en/faculty/basic-sciences-and-mathematics"> Faculty of Basic Sciences & Mathematics</a> \n                                            </li>\n                                            <li> \n                                                <a href="https://www.mul.edu.pk/en/faculty/computer-science-and-information-technology"> Faculty of Computer Science & Information Technology</a> \n                                            </li>\n                                            <li> \n                                                <a href="https://www.mul.edu.pk/en/faculty/economics-and-management-science"> Faculty of Economics & Management Sciences</a> \n                                            </li>\n                                            <li> \n                                                <a href="https://www.mul.edu.pk/en/faculty/engineering"> Faculty of Engineering</a> \n                                            </li>\n                                            <li> \n                                                <a href="https://www.mul.edu.pk/en/faculty/islamic-studies"> Faculty of Islamic Studies</a> \n                                            </li>\n                                            <li> \n                                                <a href="https://www.mul.edu.pk/en/faculty/languages"> Faculty of Languages</a> \n                                            </li>\n                                            <li> \n                                                <a href="https://www.mul.edu.pk/en/faculty/law"> Faculty of Law</a> \n                                            </li>\n                                            <li> \n                                                <a href="https://www.mul.edu.pk/en/faculty/pharmacy"> Faculty of Pharmacy</a> \n                                            </li>\n                                            <li> \n                                                <a href="https://www.mul.edu.pk/en/faculty/social-sciences-and-humanities"> Faculty of Social Sciences & Humanities</a> \n                                            </li>\n                                        </ul>\n                                    </li>\n                                    <li> <a href="https://www.mul.edu.pk/en/adjunct-faculty"> Adjunct Faculty</a> </li>\n                                    <li> <a href="https://www.mul.edu.pk/en/academic-advisement"> Academic Advisement</a> </li>\n                                    <li> <a href="https://www.mul.edu.pk/en/academic-calen

In [8]:
soup = BeautifulSoup(webpage, "lxml")

In [9]:
soup

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="ie=edge" http-equiv="x-ua-compatible"/>
<meta content="index, follow" name="robots"/>
<meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/>
<link href="https://www.mul.edu.pk/images/favicon.ico" rel="shortcut icon" type="image/png"/>
<title>All Programs - Minhaj University Lahore</title>
<link href="https://www.mul.edu.pk/images/minhaj-university-lahore.png" rel="image_src"/>
<meta content="https://www.mul.edu.pk/images/minhaj-university-lahore.png" property="og:image:url"/>
<meta content="All Programs - Minhaj University Lahore" property="og:title"/>
<meta content="Graduate Program Post Graduate Program Diploma Computer Science Information Technology Associate Degree Commerce Software Engineering Political English Urdu Physics Mathematics Chemistry International Relations Mass Communication Pakistan Studies Medical Laboratory Technology Botany Zoology Economics Accounting Finance Food" property="og:description"/>
<meta content="https://www.mul.edu.pk/en/programs" property="og:url"/>
<meta content="Minhaj University Lahore" property="og:site_name"/>
<meta content="article" property="og:type"/>
<meta content="en_US" property="og:locale"/>
<meta content="https://www.facebook.com/MinhajUniversityLahore" property="article:author"/>
<meta content="https://www.facebook.com/MinhajUniversityLahore" property="article:publisher"/>
<meta content="summary" name="twitter:card"/>
<meta content="https://www.mul.edu.pk/en/programs" name="twitter:url"/>
<meta content="All Programs - Minhaj University Lahore" name="twitter:title"/>
<meta content="All Programs - Minhaj University Lahore" name="twitter:description"/>
<meta content="https://www.mul.edu.pk/images/minhaj-university-lahore.png" name="twitter:image:src"/>
<meta content="https://www.mul.edu.pk/images/minhaj-university-lahore.png" name="twitter:image"/>
<meta content="Minhaj University Lahore" name="twitter:domain"/>
<meta content="@OfficialMUL" name="twitter:site"/>
<meta content="@OfficialMUL" name="twitter:creator"/>
<meta content="All Programs - Minhaj University Lahore" itemprop="name"/>
<meta content="Graduate Program Post Graduate Program Diploma Computer Science Information Technology Associate Degree Commerce Software Engineering Political English Urdu Physics Mathematics Chemistry International Relations Mass Communication Pakistan Studies Medical Laboratory Technology Botany Zoology Economics Accounting Finance Food" itemprop="description"/>
<meta content="https://www.mul.edu.pk/images/minhaj-university-lahore.png" itemprop="image"/>
<meta content="All Programs - Minhaj University Lahore" itemprop="alternativeHeadline"/>
<meta content="https://www.mul.edu.pk/images/minhaj-university-lahore.png" itemprop="thumbnailUrl"/>
<meta content="Graduate Program Post Graduate Program Diploma Computer Science Information Technology Associate Degree Commerce Software Engineering Political English Urdu Physics Mathematics Chemistry International Relations Mass Communication Pakistan Studies Medical Laboratory Technology Botany Zoology Economics Accounting Finance Food" name="description"/>
<meta content="Graduate, Program, Post, Graduate, Program, Diploma, Computer, Science, Information, Technology, Associate, Degree, Commerce, Software, Engineering, Political, English, Urdu, Physics, Mathematics, Chemistry, International, Relations, Mass, Communication, Pakistan, Studies, Medical, Laboratory, Technology, Botany, Zoology, Economics, Accounting, Finance, Food" name="keywords"/>
<meta content="n43oiqg2dly4sr5bgy4nbuy9md1t7e" name="facebook-domain-verification"/>
<link href="https://www.mul.edu.pk/assets/css/vendor/bootstrap.min.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/vendor/slick.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/vendor/slick-theme.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/sal.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/feather.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/fontawesome.min.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/euclid-circulara.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/swiper.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/magnify.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/odometer.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/animation.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/bootstrap-select.min.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/jquery-ui.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/magnigy-popup.min.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/style.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/zenfy/assets/css/bootstrap-icons.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/zenfy/assets/css/animate.min.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/zenfy/assets/css/jquery.fancybox.min.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/zenfy/assets/css/swiper-bundle.min.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/zenfy/assets/css/boxicons.min.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/zenfy/assets/css/style.css" rel="stylesheet"/>
<script>
		(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
		new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
		j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
		'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
		})(window,document,'script','dataLayer','GTM-N72MWHD');
	</script>
<meta content="Dr_EKInP8uQ1Hq4inIju8l5qPoWrXMFghNnXBSzAJXY" name="google-site-verification"/>
<script>
		(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3&appId=473691367168921";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, "script", "facebook-jssdk"));
    </script> <script>
        !function(f,b,e,v,n,t,s)
        {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};
        if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
        n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];
        s.parentNode.insertBefore(t,s)}(window, document,'script',
        'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '432949847984852');
        fbq('track', 'PageView');
    </script>
<noscript><img height="1" src="https://www.facebook.com/tr?id=432949847984852&amp;ev=PageView&amp;noscript=1" style="display:none" width="1"/></noscript>
</head>
<style>
    #nav {
        transition: all 0.1s ease-in-out;
    }
</style>
<body>
<noscript><iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-N72MWHD" style="display:none;visibility:hidden" width="0"></iframe></noscript>
<div class="sidebar-menu">
<div class="sidebar-menu-top-area">
<div class="container d-flex align-items-center justify-content-between">
<div class="sidebar-menu-logo">
<a class="logo-dark" href="https://www.mul.edu.pk/en/">
<img alt="mul-logo" class="img-fluid" src="https://www.mul.edu.pk/images/mul_logo.jpg" style="width: 170px;"/>
</a>
<a class="logo-light" href="https://www.mul.edu.pk/en/">
<img alt="mul-logo" class="img-fluid" src="https://www.mul.edu.pk/images/mul_logo.jpg" style="width: 170px;"/>
</a>
</div>
<div class="sidebar-menu-close">
<svg height="20" viewbox="0 0 18 18" width="20" xmlns="http://www.w3.org/2000/svg">
<path clip-rule="evenodd" d="M18 0L11.1686 8.99601L18 18L9.0041 11.1605L0 18L6.83156 8.99601L0 0L9.0041 6.83156L18 0Z" fill-rule="evenodd">
</path>
</svg>
</div>
</div>
</div>
<style>
            .main-nav-element {
                display: none;
            }
            @media Screen and (max-width: 990px) {
                .main-nav-element {
                    display: block;
                }
            }
        </style>
<div class="container">
<div class="row g-lg-4 gy-5">
<div class="col-lg-8">
<div class="sidebar-menu-wrap">
<ul class="main-menu">
<li class="main-nav-element">
<a href="https://www.mul.edu.pk/en/">Home</a>
</li>
<li class="main-nav-element">
<a href="#">About </a>
<span class="dropdown-icon2"><i class="bi bi-plus"></i></span>
<ul class="submenu-list">
<li>
<a href="#"> Leadership &amp; <br/> Governance</a>
<span class="dropdown-icon2" style="position: absolute !important; top: 0;"><i class="bi bi-plus"></i></span>
<ul class="submenu-list">
<li>
<a href="https://www.mul.edu.pk/en/welcome-message/welcome-from-the-chairman-board-of-governors-bog"> Chairman</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/welcome-message/message-from-the-deputy-chairman-bog"> Deputy Chairman</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/welcome-message/message-from-the-vice-chancellor"> Vice Chancellor</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/deans"> Deans</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/directors"> Directors</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/hods"> Head of Schools</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/bogs"> Board of Governors</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/academic-council"> Academic Council</a>
</li>
<li>
<a href="#"> Officers of MUL</a>
<span class="dropdown-icon2" style="position: absolute !important; top: 0;"><i class="bi bi-plus"></i></span>
<ul class="submenu-list">
<!--<li>
                                                        <a href="#"> Office of the Vice Chancellor</a>
                                                    </li> -->
<li>
<a href="https://www.mul.edu.pk/en/office-of-registrar"> Office of the Registrar</a>
</li>
<!--<li>
                                                        <a href="#"> Office of the Treasurer</a>
                                                    </li>
                                                    <li>
                                                        <a href="#"> Office of Controller of Examination</a>
                                                    </li> -->
</ul>
</li>
</ul>
</li>
<li> <a href="https://www.mul.edu.pk/en/about"> About MUL</a> </li>
<li> <a href="https://www.mul.edu.pk/en/mul-at-glance"> MUL at a Glance</a> </li>
<li> <a href="https://dgl.mul.edu.pk/" target="_blank"> Global Linkages</a> </li>
</ul>
</li>
<li class="main-nav-element">
<a href="https://www.mul.edu.pk/en/news-events">News &amp; Events</a>
</li>
<li class="main-nav-element">
<a href="#">Admissions </a>
<span class="dropdown-icon2 active"><i class="bi bi-plus"></i></span>
<ul class="submenu-list active">
<li> <a href="https://www.mul.edu.pk/en/programs"> All Programs</a></li>
<li> <a href="https://www.mul.edu.pk/en/programs/bs-programs"> BS Programs</a></li>
<li> <a href="https://www.mul.edu.pk/en/programs/mphil-programs"> M.Phil Programs</a></li>
<li> <a href="https://www.mul.edu.pk/en/programs/phd-programs"> Ph.D. Programs</a></li>
<li> <a href="https://www.mul.edu.pk/en/fee-calculator"> Fee Calculator</a></li>
<li> <a href="https://www.mul.edu.pk/en/scholarships-and-fee-concession"> Financial Aids &amp; Scholarships</a></li>
<li> <a href="https://www.mul.edu.pk/en/admission-guide"> Admission Guide</a></li>
<li> <a href="https://www.mul.edu.pk/en/admission-policy"> Admission Policy</a></li>
<li> <a href="https://www.mul.edu.pk/downloads/MUL_Prospectus.pdf"> Prospectus</a></li>
<li> <a href="https://admission.mul.edu.pk/"> Apply Now</a></li>
</ul>
</li>
<li class="main-nav-element">
<a href="https://www.mul.edu.pk/en/contact">Contact</a>
</li>
<li>
<a href="#">Academics </a>
<span class="dropdown-icon2 active"><i class="bi bi-plus"></i></span>
<ul class="submenu-list active">
<li>
<a href="#"> Faculties</a>
<span class="dropdown-icon2" style="position: absolute !important; top: 0;"><i class="bi bi-plus"></i></span>
<ul class="submenu-list">
<li>
<a href="https://www.mul.edu.pk/en/faculty/health-sciences"> Faculty of Allied Health Sciences</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/applied-sciences"> Faculty of Applied Sciences</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/art-designing-and-architecture"> Faculty of Art, Designing, &amp; Architecture</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/basic-sciences-and-mathematics"> Faculty of Basic Sciences &amp; Mathematics</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/computer-science-and-information-technology"> Faculty of Computer Science &amp; Information Technology</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/economics-and-management-science"> Faculty of Economics &amp; Management Sciences</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/engineering"> Faculty of Engineering</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/islamic-studies"> Faculty of Islamic Studies</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/languages"> Faculty of Languages</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/law"> Faculty of Law</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/pharmacy"> Faculty of Pharmacy</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/social-sciences-and-humanities"> Faculty of Social Sciences &amp; Humanities</a>
</li>
</ul>
</li>
<li> <a href="https://www.mul.edu.pk/en/adjunct-faculty"> Adjunct Faculty</a> </li>
<li> <a href="https://www.mul.edu.pk/en/academic-advisement"> Academic Advisement</a> </li>
<li> <a href="https://www.mul.edu.pk/en/academic-calendar"> Academic Calendar</a> </li>
<li> <a href="https://www.mul.edu.pk/downloads/rules-and-regulations.pdf" target="_blank"> Rules &amp; Regulations</a> </li>
</ul>
</li>
<li>
<a href="#">Research</a>
<span class="dropdown-icon2"><i class="bi bi-plus"></i></span>
<ul class="submenu-list">
<li>
<a href="https://www.mul.edu.pk/en/research-centers/"> Research Centers</a>
<span class="dropdown-icon2" style="position: absolute !important; top: 0;"><i class="bi bi-plus"></i></span>
<ul class="submenu-list">
<li>
<a href="https://www.mul.edu.pk/en/news-events/center-for-research-and-development"> Center for Research and Development</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/center-of-islamic-arts-and-crafts"> Center of Islamic Arts and Crafts </a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/centre-for-economic-planning-and-development-cepd"> Centre for Economic Planning and Development (CEPD)</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/centre-for-halal-awareness-research-and-training"> Centre for Halal Awareness, Research and Training</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/centre-of-research-and-innovation-in-maritime-affairs"> Centre of Research and Innovation in Maritime Affairs </a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/corpus-research-centre"> Corpus Research Centre</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/directorate-of-open-and-distance-learning-dodl"> Directorate of Open and Distance Learning (DODL)</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/english-language-center"> English Language Center</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/farid-e-millat-research-institute"> Farid-e-Millat Research Institute</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/hassan-bin-thabit-center-for-research-in-nat-literature"> Hassan-bin-Thabit Center for Research in Na’t Literature</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/international-center-for-research-in-islamic-economics"> International Center for Research in Islamic Economics</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/international-center-of-excellence"> International Center of Excellence</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/office-of-research-innovation-commercialization"> Office of Research, Innovation &amp; Commercialization</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/shaykh-ul-islam-institute-of-spiritual-studies"> Shaykh ul Islam Institute of Spiritual Studies</a>
</li>
</ul>
</li>
<li><a href="https://www.mul.edu.pk/en/journals/">Research Journals</a></li>
<li><a href="https://www.mul.edu.pk/en/conferences/">Conferences</a></li>
<li><a href="https://www.mul.edu.pk/en/publications/">Publications</a></li>
<!-- <li><a href="https://www.mul.edu.pk/en/research-labs/">Research Labs</a></li> -->
<li>
<a href="#"> Policies</a>
<span class="dropdown-icon2" style="position: absolute !important; top: 0;"><i class="bi bi-plus"></i></span>
<ul class="submenu-list">
<li>
<a href="https://www.mul.edu.pk/downloads/pitman_proposal.pdf" target="_blank"> Pitman Proposal</a>
</li>
<li>
<a href="https://www.mul.edu.pk/downloads/plagiarism_policy.pdf" target="_blank"> Plagiarism Policy</a>
</li>
<li>
<a href="https://www.mul.edu.pk/downloads/research_proposal.pdf" target="_blank"> Research Proposal</a>
</li>
</ul>
</li>
</ul>
</li>
<li>
<a href="#">Campus Life</a>
<span class="dropdown-icon2"><i class="bi bi-plus"></i></span>
<ul class="submenu-list">
<li> <a href="https://www.mul.edu.pk/en/students-perspectives" style="text-transform: none !important;"> Student`s Perspective</a> </li>
<li> <a href="https://www.mul.edu.pk/en/campus-facilities" style="text-transform: none !important;"> Campus Facilities</a> </li>
<li> <a href="https://www.mul.edu.pk/en/seekers-club" style="text-transform: none !important;"> Seekers Club &amp; Societies</a> </li>
<li> <a href="https://www.mul.edu.pk/en/campus-tour" style="text-transform: none !important;"> Campus Tour</a> </li>
</ul>
</li>
<!--
                            <li>
                                <a href="https://www.mul.edu.pk/en/directorates">Directorates</a>
                                <span class="dropdown-icon2"><i class="bi bi-plus"></i></span>
                                <ul class="submenu-list">
                                    <li>
                                        <a href="https://www.mul.edu.pk/en/directorate-of-student-affairs" target="_blank"> Directorate of Student Affairs</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="https://www.mul.edu.pk/en/alumni">ALUMNI</a>
                            </li>
                            -->
<li>
<a href="https://minhaj.rozee.pk/" target="_blank">MUL Jobs Employment Portal</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/downloads">Downloads</a>
</li>
<li>
<a href="https://career.mul.edu.pk">Career</a>
</li>
</ul>
</div>
</div>
<div class="col-lg-4 d-lg-flex">
<div class="sidebar-contact">
<div class="getin-touch-area mb-60">
<h4>Get in Touch
                                <svg height="12" viewbox="0 0 12 12" width="12" xmlns="http://www.w3.org/2000/svg">
<path d="M10.0035 3.40804L1.41153 12L0 10.5885L8.59097 1.99651H1.01922V0H12V10.9808H10.0035V3.40804Z"></path>
</svg>
</h4>
<ul>
<li class="single-contact">
<div class="icon">
<svg height="18" viewbox="0 0 18 18" width="18" xmlns="http://www.w3.org/2000/svg">

In [10]:
soup.prettify

<bound method Tag.prettify of <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="ie=edge" http-equiv="x-ua-compatible"/>
<meta content="index, follow" name="robots"/>
<meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/>
<link href="https://www.mul.edu.pk/images/favicon.ico" rel="shortcut icon" type="image/png"/>
<title>All Programs - Minhaj University Lahore</title>
<link href="https://www.mul.edu.pk/images/minhaj-university-lahore.png" rel="image_src"/>
<meta content="https://www.mul.edu.pk/images/minhaj-university-lahore.png" property="og:image:url"/>
<meta content="All Programs - Minhaj University Lahore" property="og:title"/>
<meta content="Graduate Program Post Graduate Program Diploma Computer Science Information Technology Associate Degree Commerce Software Engineering Political English Urdu Physics Mathematics Chemistry International Relations Mass Communication Pakistan Studies Medical Laboratory Technology Botany Zoology Economics Accounting Finance Food" property="og:description"/>
<meta content="https://www.mul.edu.pk/en/programs" property="og:url"/>
<meta content="Minhaj University Lahore" property="og:site_name"/>
<meta content="article" property="og:type"/>
<meta content="en_US" property="og:locale"/>
<meta content="https://www.facebook.com/MinhajUniversityLahore" property="article:author"/>
<meta content="https://www.facebook.com/MinhajUniversityLahore" property="article:publisher"/>
<meta content="summary" name="twitter:card"/>
<meta content="https://www.mul.edu.pk/en/programs" name="twitter:url"/>
<meta content="All Programs - Minhaj University Lahore" name="twitter:title"/>
<meta content="All Programs - Minhaj University Lahore" name="twitter:description"/>
<meta content="https://www.mul.edu.pk/images/minhaj-university-lahore.png" name="twitter:image:src"/>
<meta content="https://www.mul.edu.pk/images/minhaj-university-lahore.png" name="twitter:image"/>
<meta content="Minhaj University Lahore" name="twitter:domain"/>
<meta content="@OfficialMUL" name="twitter:site"/>
<meta content="@OfficialMUL" name="twitter:creator"/>
<meta content="All Programs - Minhaj University Lahore" itemprop="name"/>
<meta content="Graduate Program Post Graduate Program Diploma Computer Science Information Technology Associate Degree Commerce Software Engineering Political English Urdu Physics Mathematics Chemistry International Relations Mass Communication Pakistan Studies Medical Laboratory Technology Botany Zoology Economics Accounting Finance Food" itemprop="description"/>
<meta content="https://www.mul.edu.pk/images/minhaj-university-lahore.png" itemprop="image"/>
<meta content="All Programs - Minhaj University Lahore" itemprop="alternativeHeadline"/>
<meta content="https://www.mul.edu.pk/images/minhaj-university-lahore.png" itemprop="thumbnailUrl"/>
<meta content="Graduate Program Post Graduate Program Diploma Computer Science Information Technology Associate Degree Commerce Software Engineering Political English Urdu Physics Mathematics Chemistry International Relations Mass Communication Pakistan Studies Medical Laboratory Technology Botany Zoology Economics Accounting Finance Food" name="description"/>
<meta content="Graduate, Program, Post, Graduate, Program, Diploma, Computer, Science, Information, Technology, Associate, Degree, Commerce, Software, Engineering, Political, English, Urdu, Physics, Mathematics, Chemistry, International, Relations, Mass, Communication, Pakistan, Studies, Medical, Laboratory, Technology, Botany, Zoology, Economics, Accounting, Finance, Food" name="keywords"/>
<meta content="n43oiqg2dly4sr5bgy4nbuy9md1t7e" name="facebook-domain-verification"/>
<link href="https://www.mul.edu.pk/assets/css/vendor/bootstrap.min.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/vendor/slick.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/vendor/slick-theme.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/sal.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/feather.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/fontawesome.min.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/euclid-circulara.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/swiper.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/magnify.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/odometer.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/animation.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/bootstrap-select.min.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/jquery-ui.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/plugins/magnigy-popup.min.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/css/style.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/zenfy/assets/css/bootstrap-icons.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/zenfy/assets/css/animate.min.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/zenfy/assets/css/jquery.fancybox.min.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/zenfy/assets/css/swiper-bundle.min.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/zenfy/assets/css/boxicons.min.css" rel="stylesheet"/>
<link href="https://www.mul.edu.pk/assets/zenfy/assets/css/style.css" rel="stylesheet"/>
<script>
		(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
		new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
		j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
		'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
		})(window,document,'script','dataLayer','GTM-N72MWHD');
	</script>
<meta content="Dr_EKInP8uQ1Hq4inIju8l5qPoWrXMFghNnXBSzAJXY" name="google-site-verification"/>
<script>
		(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3&appId=473691367168921";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, "script", "facebook-jssdk"));
    </script> <script>
        !function(f,b,e,v,n,t,s)
        {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};
        if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
        n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];
        s.parentNode.insertBefore(t,s)}(window, document,'script',
        'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '432949847984852');
        fbq('track', 'PageView');
    </script>
<noscript><img height="1" src="https://www.facebook.com/tr?id=432949847984852&amp;ev=PageView&amp;noscript=1" style="display:none" width="1"/></noscript>
</head>
<style>
    #nav {
        transition: all 0.1s ease-in-out;
    }
</style>
<body>
<noscript><iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-N72MWHD" style="display:none;visibility:hidden" width="0"></iframe></noscript>
<div class="sidebar-menu">
<div class="sidebar-menu-top-area">
<div class="container d-flex align-items-center justify-content-between">
<div class="sidebar-menu-logo">
<a class="logo-dark" href="https://www.mul.edu.pk/en/">
<img alt="mul-logo" class="img-fluid" src="https://www.mul.edu.pk/images/mul_logo.jpg" style="width: 170px;"/>
</a>
<a class="logo-light" href="https://www.mul.edu.pk/en/">
<img alt="mul-logo" class="img-fluid" src="https://www.mul.edu.pk/images/mul_logo.jpg" style="width: 170px;"/>
</a>
</div>
<div class="sidebar-menu-close">
<svg height="20" viewbox="0 0 18 18" width="20" xmlns="http://www.w3.org/2000/svg">
<path clip-rule="evenodd" d="M18 0L11.1686 8.99601L18 18L9.0041 11.1605L0 18L6.83156 8.99601L0 0L9.0041 6.83156L18 0Z" fill-rule="evenodd">
</path>
</svg>
</div>
</div>
</div>
<style>
            .main-nav-element {
                display: none;
            }
            @media Screen and (max-width: 990px) {
                .main-nav-element {
                    display: block;
                }
            }
        </style>
<div class="container">
<div class="row g-lg-4 gy-5">
<div class="col-lg-8">
<div class="sidebar-menu-wrap">
<ul class="main-menu">
<li class="main-nav-element">
<a href="https://www.mul.edu.pk/en/">Home</a>
</li>
<li class="main-nav-element">
<a href="#">About </a>
<span class="dropdown-icon2"><i class="bi bi-plus"></i></span>
<ul class="submenu-list">
<li>
<a href="#"> Leadership &amp; <br/> Governance</a>
<span class="dropdown-icon2" style="position: absolute !important; top: 0;"><i class="bi bi-plus"></i></span>
<ul class="submenu-list">
<li>
<a href="https://www.mul.edu.pk/en/welcome-message/welcome-from-the-chairman-board-of-governors-bog"> Chairman</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/welcome-message/message-from-the-deputy-chairman-bog"> Deputy Chairman</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/welcome-message/message-from-the-vice-chancellor"> Vice Chancellor</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/deans"> Deans</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/directors"> Directors</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/hods"> Head of Schools</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/bogs"> Board of Governors</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/academic-council"> Academic Council</a>
</li>
<li>
<a href="#"> Officers of MUL</a>
<span class="dropdown-icon2" style="position: absolute !important; top: 0;"><i class="bi bi-plus"></i></span>
<ul class="submenu-list">
<!--<li>
                                                        <a href="#"> Office of the Vice Chancellor</a>
                                                    </li> -->
<li>
<a href="https://www.mul.edu.pk/en/office-of-registrar"> Office of the Registrar</a>
</li>
<!--<li>
                                                        <a href="#"> Office of the Treasurer</a>
                                                    </li>
                                                    <li>
                                                        <a href="#"> Office of Controller of Examination</a>
                                                    </li> -->
</ul>
</li>
</ul>
</li>
<li> <a href="https://www.mul.edu.pk/en/about"> About MUL</a> </li>
<li> <a href="https://www.mul.edu.pk/en/mul-at-glance"> MUL at a Glance</a> </li>
<li> <a href="https://dgl.mul.edu.pk/" target="_blank"> Global Linkages</a> </li>
</ul>
</li>
<li class="main-nav-element">
<a href="https://www.mul.edu.pk/en/news-events">News &amp; Events</a>
</li>
<li class="main-nav-element">
<a href="#">Admissions </a>
<span class="dropdown-icon2 active"><i class="bi bi-plus"></i></span>
<ul class="submenu-list active">
<li> <a href="https://www.mul.edu.pk/en/programs"> All Programs</a></li>
<li> <a href="https://www.mul.edu.pk/en/programs/bs-programs"> BS Programs</a></li>
<li> <a href="https://www.mul.edu.pk/en/programs/mphil-programs"> M.Phil Programs</a></li>
<li> <a href="https://www.mul.edu.pk/en/programs/phd-programs"> Ph.D. Programs</a></li>
<li> <a href="https://www.mul.edu.pk/en/fee-calculator"> Fee Calculator</a></li>
<li> <a href="https://www.mul.edu.pk/en/scholarships-and-fee-concession"> Financial Aids &amp; Scholarships</a></li>
<li> <a href="https://www.mul.edu.pk/en/admission-guide"> Admission Guide</a></li>
<li> <a href="https://www.mul.edu.pk/en/admission-policy"> Admission Policy</a></li>
<li> <a href="https://www.mul.edu.pk/downloads/MUL_Prospectus.pdf"> Prospectus</a></li>
<li> <a href="https://admission.mul.edu.pk/"> Apply Now</a></li>
</ul>
</li>
<li class="main-nav-element">
<a href="https://www.mul.edu.pk/en/contact">Contact</a>
</li>
<li>
<a href="#">Academics </a>
<span class="dropdown-icon2 active"><i class="bi bi-plus"></i></span>
<ul class="submenu-list active">
<li>
<a href="#"> Faculties</a>
<span class="dropdown-icon2" style="position: absolute !important; top: 0;"><i class="bi bi-plus"></i></span>
<ul class="submenu-list">
<li>
<a href="https://www.mul.edu.pk/en/faculty/health-sciences"> Faculty of Allied Health Sciences</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/applied-sciences"> Faculty of Applied Sciences</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/art-designing-and-architecture"> Faculty of Art, Designing, &amp; Architecture</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/basic-sciences-and-mathematics"> Faculty of Basic Sciences &amp; Mathematics</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/computer-science-and-information-technology"> Faculty of Computer Science &amp; Information Technology</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/economics-and-management-science"> Faculty of Economics &amp; Management Sciences</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/engineering"> Faculty of Engineering</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/islamic-studies"> Faculty of Islamic Studies</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/languages"> Faculty of Languages</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/law"> Faculty of Law</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/pharmacy"> Faculty of Pharmacy</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/faculty/social-sciences-and-humanities"> Faculty of Social Sciences &amp; Humanities</a>
</li>
</ul>
</li>
<li> <a href="https://www.mul.edu.pk/en/adjunct-faculty"> Adjunct Faculty</a> </li>
<li> <a href="https://www.mul.edu.pk/en/academic-advisement"> Academic Advisement</a> </li>
<li> <a href="https://www.mul.edu.pk/en/academic-calendar"> Academic Calendar</a> </li>
<li> <a href="https://www.mul.edu.pk/downloads/rules-and-regulations.pdf" target="_blank"> Rules &amp; Regulations</a> </li>
</ul>
</li>
<li>
<a href="#">Research</a>
<span class="dropdown-icon2"><i class="bi bi-plus"></i></span>
<ul class="submenu-list">
<li>
<a href="https://www.mul.edu.pk/en/research-centers/"> Research Centers</a>
<span class="dropdown-icon2" style="position: absolute !important; top: 0;"><i class="bi bi-plus"></i></span>
<ul class="submenu-list">
<li>
<a href="https://www.mul.edu.pk/en/news-events/center-for-research-and-development"> Center for Research and Development</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/center-of-islamic-arts-and-crafts"> Center of Islamic Arts and Crafts </a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/centre-for-economic-planning-and-development-cepd"> Centre for Economic Planning and Development (CEPD)</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/centre-for-halal-awareness-research-and-training"> Centre for Halal Awareness, Research and Training</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/centre-of-research-and-innovation-in-maritime-affairs"> Centre of Research and Innovation in Maritime Affairs </a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/corpus-research-centre"> Corpus Research Centre</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/directorate-of-open-and-distance-learning-dodl"> Directorate of Open and Distance Learning (DODL)</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/english-language-center"> English Language Center</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/farid-e-millat-research-institute"> Farid-e-Millat Research Institute</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/hassan-bin-thabit-center-for-research-in-nat-literature"> Hassan-bin-Thabit Center for Research in Na’t Literature</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/international-center-for-research-in-islamic-economics"> International Center for Research in Islamic Economics</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/international-center-of-excellence"> International Center of Excellence</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/office-of-research-innovation-commercialization"> Office of Research, Innovation &amp; Commercialization</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/news-events/shaykh-ul-islam-institute-of-spiritual-studies"> Shaykh ul Islam Institute of Spiritual Studies</a>
</li>
</ul>
</li>
<li><a href="https://www.mul.edu.pk/en/journals/">Research Journals</a></li>
<li><a href="https://www.mul.edu.pk/en/conferences/">Conferences</a></li>
<li><a href="https://www.mul.edu.pk/en/publications/">Publications</a></li>
<!-- <li><a href="https://www.mul.edu.pk/en/research-labs/">Research Labs</a></li> -->
<li>
<a href="#"> Policies</a>
<span class="dropdown-icon2" style="position: absolute !important; top: 0;"><i class="bi bi-plus"></i></span>
<ul class="submenu-list">
<li>
<a href="https://www.mul.edu.pk/downloads/pitman_proposal.pdf" target="_blank"> Pitman Proposal</a>
</li>
<li>
<a href="https://www.mul.edu.pk/downloads/plagiarism_policy.pdf" target="_blank"> Plagiarism Policy</a>
</li>
<li>
<a href="https://www.mul.edu.pk/downloads/research_proposal.pdf" target="_blank"> Research Proposal</a>
</li>
</ul>
</li>
</ul>
</li>
<li>
<a href="#">Campus Life</a>
<span class="dropdown-icon2"><i class="bi bi-plus"></i></span>
<ul class="submenu-list">
<li> <a href="https://www.mul.edu.pk/en/students-perspectives" style="text-transform: none !important;"> Student`s Perspective</a> </li>
<li> <a href="https://www.mul.edu.pk/en/campus-facilities" style="text-transform: none !important;"> Campus Facilities</a> </li>
<li> <a href="https://www.mul.edu.pk/en/seekers-club" style="text-transform: none !important;"> Seekers Club &amp; Societies</a> </li>
<li> <a href="https://www.mul.edu.pk/en/campus-tour" style="text-transform: none !important;"> Campus Tour</a> </li>
</ul>
</li>
<!--
                            <li>
                                <a href="https://www.mul.edu.pk/en/directorates">Directorates</a>
                                <span class="dropdown-icon2"><i class="bi bi-plus"></i></span>
                                <ul class="submenu-list">
                                    <li>
                                        <a href="https://www.mul.edu.pk/en/directorate-of-student-affairs" target="_blank"> Directorate of Student Affairs</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="https://www.mul.edu.pk/en/alumni">ALUMNI</a>
                            </li>
                            -->
<li>
<a href="https://minhaj.rozee.pk/" target="_blank">MUL Jobs Employment Portal</a>
</li>
<li>
<a href="https://www.mul.edu.pk/en/downloads">Downloads</a>
</li>
<li>
<a href="https://career.mul.edu.pk">Career</a>
</li>
</ul>
</div>
</div>
<div class="col-lg-4 d-lg-flex">
<div class="sidebar-contact">
<div class="getin-touch-area mb-60">
<h4>Get in Touch
                                <svg height="12" viewbox="0 0 12 12" width="12" xmlns="http://www.w3.org/2000/svg">
<path d="M10.0035 3.40804L1.41153 12L0 10.5885L8.59097 1.99651H1.01922V0H12V10.9808H10.0035V3.40804Z"></path>
</svg>
</h4>
<ul>
<li class="single-contact">
<div class="icon">
<svg height="18" viewbox="0 0 18 18" width="18" xmlns="http://www.w3.org/2000/svg">

In [14]:
soup.find_all("h1")[0].text

'Programs Offered  By Minhaj University Lahore'

In [16]:
len(soup.find_all("h2"))

1

In [17]:
soup.find_all("a")

[<a class="logo-dark" href="https://www.mul.edu.pk/en/">
 <img alt="mul-logo" class="img-fluid" src="https://www.mul.edu.pk/images/mul_logo.jpg" style="width: 170px;"/>
 </a>,
 <a class="logo-light" href="https://www.mul.edu.pk/en/">
 <img alt="mul-logo" class="img-fluid" src="https://www.mul.edu.pk/images/mul_logo.jpg" style="width: 170px;"/>
 </a>,
 <a href="https://www.mul.edu.pk/en/">Home</a>,
 <a href="#">About </a>,
 <a href="#"> Leadership &amp; <br/> Governance</a>,
 <a href="https://www.mul.edu.pk/en/welcome-message/welcome-from-the-chairman-board-of-governors-bog"> Chairman</a>,
 <a href="https://www.mul.edu.pk/en/welcome-message/message-from-the-deputy-chairman-bog"> Deputy Chairman</a>,
 <a href="https://www.mul.edu.pk/en/welcome-message/message-from-the-vice-chancellor"> Vice Chancellor</a>,
 <a href="https://www.mul.edu.pk/en/deans"> Deans</a>,
 <a href="https://www.mul.edu.pk/en/directors"> Directors</a>,
 <a href="https://www.mul.edu.pk/en/hods"> Head of Schools</a>,
 <a href="https://www.mul.edu.pk/en/bogs"> Board of Governors</a>,
 <a href="https://www.mul.edu.pk/en/academic-council"> Academic Council</a>,
 <a href="#"> Officers of MUL</a>,
 <a href="https://www.mul.edu.pk/en/office-of-registrar"> Office of the Registrar</a>,
 <a href="https://www.mul.edu.pk/en/about"> About MUL</a>,
 <a href="https://www.mul.edu.pk/en/mul-at-glance"> MUL at a Glance</a>,
 <a href="https://dgl.mul.edu.pk/" target="_blank"> Global Linkages</a>,
 <a href="https://www.mul.edu.pk/en/news-events">News &amp; Events</a>,
 <a href="#">Admissions </a>,
 <a href="https://www.mul.edu.pk/en/programs"> All Programs</a>,
 <a href="https://www.mul.edu.pk/en/programs/bs-programs"> BS Programs</a>,
 <a href="https://www.mul.edu.pk/en/programs/mphil-programs"> M.Phil Programs</a>,
 <a href="https://www.mul.edu.pk/en/programs/phd-programs"> Ph.D. Programs</a>,
 <a href="https://www.mul.edu.pk/en/fee-calculator"> Fee Calculator</a>,
 <a href="https://www.mul.edu.pk/en/scholarships-and-fee-concession"> Financial Aids &amp; Scholarships</a>,
 <a href="https://www.mul.edu.pk/en/admission-guide"> Admission Guide</a>,
 <a href="https://www.mul.edu.pk/en/admission-policy"> Admission Policy</a>,
 <a href="https://www.mul.edu.pk/downloads/MUL_Prospectus.pdf"> Prospectus</a>,
 <a href="https://admission.mul.edu.pk/"> Apply Now</a>,
 <a href="https://www.mul.edu.pk/en/contact">Contact</a>,
 <a href="#">Academics </a>,
 <a href="#"> Faculties</a>,
 <a href="https://www.mul.edu.pk/en/faculty/health-sciences"> Faculty of Allied Health Sciences</a>,
 <a href="https://www.mul.edu.pk/en/faculty/applied-sciences"> Faculty of Applied Sciences</a>,
 <a href="https://www.mul.edu.pk/en/faculty/art-designing-and-architecture"> Faculty of Art, Designing, &amp; Architecture</a>,
 <a href="https://www.mul.edu.pk/en/faculty/basic-sciences-and-mathematics"> Faculty of Basic Sciences &amp; Mathematics</a>,
 <a href="https://www.mul.edu.pk/en/faculty/computer-science-and-information-technology"> Faculty of Computer Science &amp; Information Technology</a>,
 <a href="https://www.mul.edu.pk/en/faculty/economics-and-management-science"> Faculty of Economics &amp; Management Sciences</a>,
 <a href="https://www.mul.edu.pk/en/faculty/engineering"> Faculty of Engineering</a>,
 <a href="https://www.mul.edu.pk/en/faculty/islamic-studies"> Faculty of Islamic Studies</a>,
 <a href="https://www.mul.edu.pk/en/faculty/languages"> Faculty of Languages</a>,
 <a href="https://www.mul.edu.pk/en/faculty/law"> Faculty of Law</a>,
 <a href="https://www.mul.edu.pk/en/faculty/pharmacy"> Faculty of Pharmacy</a>,
 <a href="https://www.mul.edu.pk/en/faculty/social-sciences-and-humanities"> Faculty of Social Sciences &amp; Humanities</a>,
 <a href="https://www.mul.edu.pk/en/adjunct-faculty"> Adjunct Faculty</a>,
 <a href="https://www.mul.edu.pk/en/academic-advisement"> Academic Advisement</a>,
 <a href="https://www.mul.edu.pk/en/academic-calendar"> Academic Calendar</a>,
 <a href="https://www.mul.edu.pk/downloads/rules-and-regulations.pdf" target="_blank"> Rules &amp; Regulations</a>,
 <a href="#">Research</a>,
 <a href="https://www.mul.edu.pk/en/research-centers/"> Research Centers</a>,
 <a href="https://www.mul.edu.pk/en/news-events/center-for-research-and-development"> Center for Research and Development</a>,
 <a href="https://www.mul.edu.pk/en/news-events/center-of-islamic-arts-and-crafts"> Center of Islamic Arts and Crafts </a>,
 <a href="https://www.mul.edu.pk/en/news-events/centre-for-economic-planning-and-development-cepd"> Centre for Economic Planning and Development (CEPD)</a>,
 <a href="https://www.mul.edu.pk/en/news-events/centre-for-halal-awareness-research-and-training"> Centre for Halal Awareness, Research and Training</a>,
 <a href="https://www.mul.edu.pk/en/news-events/centre-of-research-and-innovation-in-maritime-affairs"> Centre of Research and Innovation in Maritime Affairs </a>,
 <a href="https://www.mul.edu.pk/en/news-events/corpus-research-centre"> Corpus Research Centre</a>,
 <a href="https://www.mul.edu.pk/en/news-events/directorate-of-open-and-distance-learning-dodl"> Directorate of Open and Distance Learning (DODL)</a>,
 <a href="https://www.mul.edu.pk/en/news-events/english-language-center"> English Language Center</a>,
 <a href="https://www.mul.edu.pk/en/news-events/farid-e-millat-research-institute"> Farid-e-Millat Research Institute</a>,
 <a href="https://www.mul.edu.pk/en/news-events/hassan-bin-thabit-center-for-research-in-nat-literature"> Hassan-bin-Thabit Center for Research in Na’t Literature</a>,
 <a href="https://www.mul.edu.pk/en/news-events/international-center-for-research-in-islamic-economics"> International Center for Research in Islamic Economics</a>,
 <a href="https://www.mul.edu.pk/en/news-events/international-center-of-excellence"> International Center of Excellence</a>,
 <a href="https://www.mul.edu.pk/en/news-events/office-of-research-innovation-commercialization"> Office of Research, Innovation &amp; Commercialization</a>,
 <a href="https://www.mul.edu.pk/en/news-events/shaykh-ul-islam-institute-of-spiritual-studies"> Shaykh ul Islam Institute of Spiritual Studies</a>,
 <a href="https://www.mul.edu.pk/en/journals/">Research Journals</a>,
 <a href="https://www.mul.edu.pk/en/conferences/">Conferences</a>,
 <a href="https://www.mul.edu.pk/en/publications/">Publications</a>,
 <a href="#"> Policies</a>,
 <a href="https://www.mul.edu.pk/downloads/pitman_proposal.pdf" target="_blank"> Pitman Proposal</a>,
 <a href="https://www.mul.edu.pk/downloads/plagiarism_policy.pdf" target="_blank"> Plagiarism Policy</a>,
 <a href="https://www.mul.edu.pk/downloads/research_proposal.pdf" target="_blank"> Research Proposal</a>,
 <a href="#">Campus Life</a>,
 <a href="https://www.mul.edu.pk/en/students-perspectives" style="text-transform: none !important;"> Student`s Perspective</a>,
 <a href="https://www.mul.edu.pk/en/campus-facilities" style="text-transform: none !important;"> Campus Facilities</a>,
 <a href="https://www.mul.edu.pk/en/seekers-club" style="text-transform: none !important;"> Seekers Club &amp; Societies</a>,
 <a href="https://www.mul.edu.pk/en/campus-tour" style="text-transform: none !important;"> Campus Tour</a>,
 <a href="https://minhaj.rozee.pk/" target="_blank">MUL Jobs Employment Portal</a>,
 <a href="https://www.mul.edu.pk/en/downloads">Downloads</a>,
 <a href="https://career.mul.edu.pk">Career</a>,
 <a href="tel:+9242351456219"><span>(+92) 42 35145621-9</span></a>,
 <a href="tel:+923111181685"><span>03 111 222 685</span></a>,
 <a href="#"><span class="__cf_email__" data-cfemail="147d7a727b54716c75796478717379757d783a777b79">info@mul.edu.pk</span></a>,
 <a href="#"><span class="__cf_email__" data-cfemail="147d7a727b54716c75796478717379757d783a777b79">admission@mul.edu.pk</span></a>,
 <a href="tel:+923111181685"><span>Let`s Talk with Admissions Representative</span></a>,
 <a href="https://twitter.com/OfficialMUL" target="_blank"><i class="bi bi-twitter-x"></i></a>,
 <a href="https://www.instagram.com/minhajuniversitylahore/" target="_blank"><i class="bi bi-instagram"></i></a>,
 <a href="https://linkedin.com/company/minhajuniversitylahore" target="_blank"><i class="bi bi-linkedin"></i></a>,
 <a href="https://www.facebook.com/MinhajUniversityLahore" target="_blank"><i class="bi bi-facebook"></i></a>,
 <a href="https://www.youtube.com/c/MinhajUniversityLahore-Official" target="_blank"><i class="bi bi-youtube"></i></a>,
 <a href="https://whatsapp.com/channel/0029VaEs5tRAjPXHCUUdTB2p" target="_blank"><i class="bi bi-whatsapp"></i></a>,
 <a class="logo-dark" href="https://www.mul.edu.pk/en/">
 <img alt="mul-logo" class="img-fluid" src="https://www.mul.edu.pk/images/logo-mul-footer.png" style="width: 200px;"/>
 </a>,
 <a href="https://www.mul.edu.pk/en/" style="color: white;">Home</a>,
 <a class="drop-down" href="#" style="color: white;">About</a>,
 <a href="#">Leaderhsip and Governance</a>,
 <a href="https://www.mul.edu.pk/en/welcome-message/welcome-from-the-chairman-board-of-governors-bog"> Chairman</a>,
 <a href="https://www.mul.edu.pk/en/welcome-message/message-from-the-deputy-chairman-bog"> Deputy Chairman</a>,
 <a href="https://www.mul.edu.pk/en/welcome-message/message-from-the-vice-chancellor"> Vice Chancellor</a>,
 <a href="https://www.mul.edu.pk/en/deans"> Deans</a>,
 <a href="https://www.mul.edu.pk/en/directors"> Directors</a>,
 <a href="https://www.mul.edu.pk/en/hods"> Heads of Schools</a>,
 <a href="https://www.mul.edu.pk/en/bogs"> Board of Governors</a>,
 <a href="https://www.mul.edu.pk/en/academic-council"> Academic Council</a>,
 <a href="#">Officers of MUL</a>,
 <a href="https://www.mul.edu.pk/en/office-of-registrar"> Office of the Registrar</a>,
 <a href="https://www.mul.edu.pk/en/about"> About MUL</a>,
 <a href="https://www.mul.edu.pk/en/mul-at-glance"> MUL at a Glance</a>,
 <a href="https://dgl.mul.edu.pk/" target="_blank"> Global Linkages</a>,
 <a href="https://www.mul.edu.pk/en/news-events" style="color: white;">News &amp; Events</a>,
 <a class="drop-down" href="#" style="color: white;">Admissions</a>,
 <a href="https://www.mul.edu.pk/en/programs"> All Programs</a>,
 <a href="https://www.mul.edu.pk/en/programs/bs-programs"> BS Programs</a>,
 <a href="https://www.mul.edu.pk/en/programs/mphil-programs"> M.Phil Programs</a>,
 <a href="https://www.mul.edu.pk/en/programs/phd-programs"> Ph.D. Programs</a>,
 <a href="https://www.mul.edu.pk/en/fee-calculator"> Fee Calculator</a>,
 <a href="https://www.mul.edu.pk/en/scholarships-and-fee-concession"> Financial Aids &amp; Scholarships</a>,
 <a href="https://www.mul.edu.pk/en/admission-guide"> Admission Guide</a>,
 <a href="https://www.mul.edu.pk/en/admission-policy"> Admission Policy</a>,
 <a href="https://www.mul.edu.pk/downloads/MUL_Prospectus.pdf" target="_blank"> Prospectus</a>,
 <a href="https://admission.mul.edu.pk/"> Apply Now</a>,
 <a href="https://www.mul.edu.pk/en/contact" style="color: white;">Contact</a>,
 <a class="primary-btn4 d-xl-flex d-none" href="https://admission.mul.edu.pk" target="_blank">
                         Apply Now
                     </a>,
 <a href="https://api.whatsapp.com/send?phone=923111181685" target="_blank">
 <svg fill="currentColor" height="20" viewbox="0 0 24 24" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M12 0C5.372 0 0 5.373 0 12c0 2.123.555 4.196 1.607 6.025L0 24l6.184-1.607A11.94 11.94 0 0 0 12 24c6.627 0 12-5.373 12-12S18.627 0 12 0zm0 21.818a9.82 9.82 0 0 1-5.001-1.373l-.357-.212-3.669.955.98-3.576-.232-.369A9.79 9.79 0 1 1 12 21.818zm5.4-7.232c-.294-.147-1.736-.857-2.005-.955-.269-.098-.465-.147-.662.147-.196.294-.759.955-.931 1.151-.172.196-.343.221-.637.074-.294-.147-1.24-.457-2.363-1.458-.874-.78-1.464-1.743-1.636-2.037-.172-.294-.018-.453.129-.6.132-.131.294-.343.441-.515.147-.172.196-.294.294-.49.098-.196.049-.368-.025-.515-.074-.147-.662-1.594-.907-2.183-.239-.575-.482-.497-.662-.506h-.565c-.196 0-.515.074-.784.368s-1.03 1.005-1.03 2.45 1.055 2.84 1.202 3.037c.147.196 2.077 3.174 5.033 4.45.704.304 1.253.486 1.68.621.705.224 1.347.192 1.854.116.566-.085 1.736-.709 1.98-1.392.245-.683.245-1.27.172-1.392-.073-.123-.269-.196-.564-.343z"></path>
 </svg>
 <span><strong>Admissions Chat</strong></span>
 </a>,
 <a href="https://web.whatsapp.com/send?phone=923111181685" target="_blank">
 <svg fill="currentColor" height="20" viewbox="0 0 24 24" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M12 0C5.372 0 0 5.373 0 12c0 2.123.555 4.196 1.607 6.025L0 24l6.184-1.607A11.94 11.94 0 0 0 12 24c6.627 0 12-5.373 12-12S18.627 0 12 0zm0 21.818a9.82 9.82 0 0 1-5.001-1.373l-.357-.212-3.669.955.98-3.576-.232-.369A9.79 9.79 0 1 1 12 21.818zm5.4-7.232c-.294-.147-1.736-.857-2.005-.955-.269-.098-.465-.147-.662.147-.196.294-.759.955-.931 1.151-.172.196-.343.221-.637.074-.294-.147-1.24-.457-2.363-1.458-.874-.78-1.464-1.743-1.636-2.037-.172-.294-.018-.453.129-.6.132-.131.294-.343.441-.515.147-.172.196-.294.294-.49.098-.196.049-.368-.025-.515-.074-.147-.662-1.594-.907-2.183-.239-.575-.482-.497-.662-.506h-.565c-.196 0-.515.074-.784.368s-1.03 1.005-1.03 2.45 1.055 2.84 1.202 3.037c.147.196 2.077 3.174 5.033 4.45.704.304 1.253.486 1.68.621.705.224 1.347.192 1.854.116.566-.085 1.736-.709 1.98-1.392.245-.683.245-1.27.172-1.392-.073-.123-.269-.196-.564-.343z"></path>
 </svg>
 <span><strong>Admissions Chat</strong></span>
 </a>,
 <a href="https://www.mul.edu.pk/en/call-me-back" style="color: white; writing-mode: vertical-rl; text-decoration: none; font-size: 14px;">
 <b>Call me Back</b>
 </a>,
 <a href="/">Home</a>,
 <a href="#adp">AD Programs</a>,
 <a href="#bs">BS Programs</a>,
 <a href="#mphil">M.Phil Programs</a>,
 <a href="#phd">Ph.D. Programs</a>,
 <a href="#short_courses">Short Courses</a>,
 <a href="https://www.mul.edu.pk/en/program/bs-human-nutrition-and-dietetics">
 <img alt="BS Human Nutrition and Dietetics" src="https://www.mul.edu.pk/images/programs/bs-human-nutrition-and-dietetics_245.jpg"/>
 </a>,
 <a href="https://www.mul.edu.pk/en/program/bs-human-nutrition-and-dietetics">BS Human Nutrition and Dietetics</a>,
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-human-nutrition-and-dietetics"> Find Out More <i class="feather-arrow-right"></i></a>,
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>,
 <a href="https://www.mul.edu.pk/en/program/bs-criminology-and-forensic-sciences">
 <img alt="BS Criminology and Forensic Sciences" src="https://www.mul.edu.pk/images/programs/bs-criminology-and-forensic-sciences_281.jpg"/>
 </a>,
 <a href="https://www.mul.edu.pk/en/program/bs-criminology-and-forensic-sciences">BS Criminology and Forensic Sciences</a>,
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-criminology-and-forensic-sciences"> Find Out More <i class="feather-arrow-right"></i></a>,
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>,
 <a href="https://www.mul.edu.pk/en/program/bs-digital-marketing">
 <img alt="BS Digital Marketing" src="https://www.mul.edu.pk/images/programs/bs-digital-marketing_286.jpg"/>
 </a>,
 <a href="https://www.mul.edu.pk/en/program/bs-digital-marketing">BS Digital Marketing</a>,
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-digital-marketing"> Find Out More <i class="feather-arrow-right"></i></a>,
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>,
 <a href="https://www.mul.edu.pk/en/program/bs-e-commerce">
 <img alt="BS E-Commerce" src="https://www.mul.edu.pk/images/programs/bs-e-commerce_302.jpg"/>
 </a>,
 <a href="https://www.mul.edu.pk/en/program/bs-e-commerce">BS E-Commerce</a>,
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-e-commerce"> Find Out More <i class="feather-arrow-right"></i></a>,
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>,
 <a href="https://www.mul.edu.pk/en/program/bs-in-digital-media-communication">
 <img alt="BS in Digital Media Communication" src="https://www.mul.edu.pk/images/programs/bs-in-digital-media-communication_311.jpg"/>
 </a>,
 <a href="https://www.mul.edu.pk/en/program/bs-in-digital-media-communication">BS in Digital Media Communication</a>,
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-in-digital-media-communication"> Find Out More <i class="feather-arrow-right"></i></a>,
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>,
 <a href="https://www.mul.edu.pk/en/program/bs-in-multimedia-arts-animation">
 <img alt="BS in Multimedia Arts- Animation" src="https://www.mul.edu.pk/images/programs/bs-in-multimedia-arts_312.jpg"/>
 </a>,
 <a href="https://www.mul.edu.pk/en/program/bs-in-multimedia-arts-animation">BS in Multimedia Arts- Animation</a>,
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-in-multimedia-arts-animation"> Find Out More <i class="feather-arrow-right"></i></a>,
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>,
 <a href="https://www.mul.edu.pk/en/program/bachelor-of-science-in-financial-technology">
 <img alt="Bachelor of Science in Financial Technology" src="https://www.mul.edu.pk/images/programs/bachelor-of-science-in-financial-technology_338.jpg"/>
 </a>,
 <a href="https://www.mul.edu.pk/en/program/bachelor-of-science-in-financial-technology">Bachelor of Science in Financial Technology</a>,
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bachelor-of-science-in-financial-technology"> Find Out More <i class="feather-arrow-right"></i></a>,
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>,
 <a href="https://www.mul.edu.pk/en/program/bs-economics-and-data-science">
 <img alt="BS Economics and Data Science" src="https://www.mul.edu.pk/images/programs/bs-economics-and-data-science_353.jpg"/>
 </a>,
 <a href="https://www.mul.edu.pk/en/program/bs-economics-and-data-science">BS Economics and Data Science</a>,
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-economics-and-data-science"> Find Out More <i class="feather-arrow-right"></i></a>,
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>,
 <a href="https://www.mul.edu.pk/en/program/bs-statistics-data-science">
 <img alt="BS Statistics &amp; Data Science" src="https://www.mul.edu.pk/images/programs/bs-statistics-data-science_358.jpg"/>
 </a>,
 <a href="https://www.mul.edu.pk/en/program/bs-statistics-data-science">BS Statistics &amp; Data Science</a>,
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-statistics-data-science"> Find Out More <i class="feather-arrow-right"></i></a>,
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>,
 <a href="https://www.mul.edu.pk/en/program/bs-computational-plant-sciences">
 <img alt="BS Computational Plant Sciences" src="https://www.mul.edu.pk/images/programs/bs-computational-plant-sciences_357.jpg"/>
 </a>,
 <a href="https://www.mul.edu.pk/en/program/bs-computational-plant-sciences">BS Computational Plant Sciences</a>,
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-computational-plant-sciences"> Find Out More <i class="feather-arrow-right"></i></a>,
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>,

In [19]:
for i in soup.find_all("a"):
    print(i.text.strip())

Home
About
Leadership &  Governance
Chairman
Deputy Chairman
Vice Chancellor
Deans
Directors
Head of Schools
Board of Governors
Academic Council
Officers of MUL
Office of the Registrar
About MUL
MUL at a Glance
Global Linkages
News & Events
Admissions
All Programs
BS Programs
M.Phil Programs
Ph.D. Programs
Fee Calculator
Financial Aids & Scholarships
Admission Guide
Admission Policy
Prospectus
Apply Now
Contact
Academics
Faculties
Faculty of Allied Health Sciences
Faculty of Applied Sciences
Faculty of Art, Designing, & Architecture
Faculty of Basic Sciences & Mathematics
Faculty of Computer Science & Information Technology
Faculty of Economics & Management Sciences
Faculty of Engineering
Faculty of Islamic Studies
Faculty of Languages
Faculty of Law
Faculty of Pharmacy
Faculty of Social Sciences & Humanities
Adjunct Faculty
Academic Advisement
Academic Calendar
Rules & Regulations
Research
Research Centers
Center for Research and Development
Center of Islamic Arts and Crafts
Centre for Economic Planning and Development (CEPD)
Centre for Halal Awareness, Research and Training
Centre of Research and Innovation in Maritime Affairs
Corpus Research Centre
Directorate of Open and Distance Learning (DODL)
English Language Center
Farid-e-Millat Research Institute
Hassan-bin-Thabit Center for Research in Na’t Literature
International Center for Research in Islamic Economics
International Center of Excellence
Office of Research, Innovation & Commercialization
Shaykh ul Islam Institute of Spiritual Studies
Research Journals
Conferences
Publications
Policies
Pitman Proposal
Plagiarism Policy
Research Proposal
Campus Life
Student`s Perspective
Campus Facilities
Seekers Club & Societies
Campus Tour
MUL Jobs Employment Portal
Downloads
Career
(+92) 42 35145621-9
03 111 222 685
info@mul.edu.pk
admission@mul.edu.pk
Let`s Talk with Admissions Representative







Home
About
Leaderhsip and Governance
Chairman
Deputy Chairman
Vice Chancellor
Deans
Directors
Heads of Schools
Board of Governors
Academic Council
Officers of MUL
Office of the Registrar
About MUL
MUL at a Glance
Global Linkages
News & Events
Admissions
All Programs
BS Programs
M.Phil Programs
Ph.D. Programs
Fee Calculator
Financial Aids & Scholarships
Admission Guide
Admission Policy
Prospectus
Apply Now
Contact
Apply Now
Admissions Chat
Admissions Chat
Call me Back
Home
AD Programs
BS Programs
M.Phil Programs
Ph.D. Programs
Short Courses

BS Human Nutrition and Dietetics
Find Out More
Apply Now

BS Criminology and Forensic Sciences
Find Out More
Apply Now

BS Digital Marketing
Find Out More
Apply Now

BS E-Commerce
Find Out More
Apply Now

BS in Digital Media Communication
Find Out More
Apply Now

BS in Multimedia Arts- Animation
Find Out More
Apply Now

Bachelor of Science in Financial Technology
Find Out More
Apply Now

BS Economics and Data Science
Find Out More
Apply Now

BS Statistics & Data Science
Find Out More
Apply Now

BS Computational Plant Sciences
Find Out More
Apply Now

BS Chemistry &  Industrial Entrepreneurship
Find Out More
Apply Now

BS Information System & Technology Management
Find Out More
Apply Now

BS Zoology and Entomology
Find Out More
Apply Now

BS Islamic Banking &  Financial Technology
Find Out More
Apply Now

BS Information Management
Find Out More
Apply Now

BS Mathematics & Data Science
Find Out More
Apply Now

BS Defense and Strategic Studies
Find Out More
Apply Now

Bachelor of Laws (LLB) 4 years
Find Out More
Apply Now

BS Business Analytics
Find Out More
Apply Now

BS Psychology
Find Out More
Apply Now

BS Aesthetics and Cosmetology
Find Out More
Apply Now

BS Computer Science
Find Out More
Apply Now

Doctor of Pharmacy
Find Out More
Apply Now

BS Information Technology
Find Out More
Apply Now

BS Software Engineering
Find Out More
Apply Now

BS Artificial Intelligence
Find Out More
Apply Now

BS Cyber Security
Find Out More
Apply Now

BBA
Find Out More
Apply Now

BS Education
Find Out More
Apply Now

BS Biotechnology
Find Out More
Apply Now

BS Data Science
Find Out More
Apply Now

BS English
Find Out More
Apply Now

BS Political Science
Find Out More
Apply Now

BS International Relations
Find Out More
Apply Now

BS Medical Laboratory Technology
Find Out More
Apply Now

BS Food Science & Technology
Find Out More
Apply Now

BS Economics
Find Out More
Apply Now

BS Economics and Financial Technology
Find Out More
Apply Now

BS Islamic Banking & Finance
Find Out More
Apply Now

B.Com (4 Year)
Find Out More
Apply Now

BS Accounting and Finance
Find Out More
Apply Now

BS Sociology
Find Out More
Apply Now

B.Sc. Chemical Engineering
Find Out More
Apply Now

B.Sc. Electrical Engineering
Find Out More
Apply Now

BS Biochemistry
Find Out More
Apply Now

BS Peace and Conflict Studies
Find Out More
Apply Now







Admissions
Programs
Scholarships & Financial Aids
Campus Facilities
Campus Tour
CMS Login
Research Centers
Research Labs
Publications
Research News
(+92) 42 35145621-9
03 111 222 685
info@mul.edu.pk


Minhaj University Lahore
Admission Policy
Rules & Regulations
Downloads
Career
Privacy Policy

In [69]:
main = soup.find_all('div', class_='rbt-card-img')

In [43]:
soup.find_all("div", class_="maso-item")

[<div class="maso-item cat--3 col-lg-4 mb--40">
 <div class="rbt-card variation-01 rbt-hover">
 <div class="rbt-card-img">
 <a href="https://www.mul.edu.pk/en/program/bs-human-nutrition-and-dietetics">
 <img alt="BS Human Nutrition and Dietetics" src="https://www.mul.edu.pk/images/programs/bs-human-nutrition-and-dietetics_245.jpg"/>
 </a>
 </div>
 <div class="rbt-card-body">
 <div class="rbt-card-top">
 <div class="rbt-review">
 <span class="rating-count"><i class="feather-book"></i> 4 Years</span>
 </div>
 </div>
 <h4 class="rbt-card-title"><a href="https://www.mul.edu.pk/en/program/bs-human-nutrition-and-dietetics">BS Human Nutrition and Dietetics</a></h4>
 <div class="rbt-card-bottom">
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-human-nutrition-and-dietetics"> Find Out More <i class="feather-arrow-right"></i></a>
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>
 </div>
 </div>
 </div>
 </div>,
 <div class="maso-item cat--3 col-lg-4 mb--40">
 <div class="rbt-card variation-01 rbt-hover">
 <div class="rbt-card-img">
 <a href="https://www.mul.edu.pk/en/program/bs-criminology-and-forensic-sciences">
 <img alt="BS Criminology and Forensic Sciences" src="https://www.mul.edu.pk/images/programs/bs-criminology-and-forensic-sciences_281.jpg"/>
 </a>
 </div>
 <div class="rbt-card-body">
 <div class="rbt-card-top">
 <div class="rbt-review">
 <span class="rating-count"><i class="feather-book"></i> 4 Years</span>
 </div>
 </div>
 <h4 class="rbt-card-title"><a href="https://www.mul.edu.pk/en/program/bs-criminology-and-forensic-sciences">BS Criminology and Forensic Sciences</a></h4>
 <div class="rbt-card-bottom">
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-criminology-and-forensic-sciences"> Find Out More <i class="feather-arrow-right"></i></a>
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>
 </div>
 </div>
 </div>
 </div>,
 <div class="maso-item cat--3 col-lg-4 mb--40">
 <div class="rbt-card variation-01 rbt-hover">
 <div class="rbt-card-img">
 <a href="https://www.mul.edu.pk/en/program/bs-digital-marketing">
 <img alt="BS Digital Marketing" src="https://www.mul.edu.pk/images/programs/bs-digital-marketing_286.jpg"/>
 </a>
 </div>
 <div class="rbt-card-body">
 <div class="rbt-card-top">
 <div class="rbt-review">
 <span class="rating-count"><i class="feather-book"></i> 4 Years</span>
 </div>
 </div>
 <h4 class="rbt-card-title"><a href="https://www.mul.edu.pk/en/program/bs-digital-marketing">BS Digital Marketing</a></h4>
 <div class="rbt-card-bottom">
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-digital-marketing"> Find Out More <i class="feather-arrow-right"></i></a>
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>
 </div>
 </div>
 </div>
 </div>,
 <div class="maso-item cat--3 col-lg-4 mb--40">
 <div class="rbt-card variation-01 rbt-hover">
 <div class="rbt-card-img">
 <a href="https://www.mul.edu.pk/en/program/bs-e-commerce">
 <img alt="BS E-Commerce" src="https://www.mul.edu.pk/images/programs/bs-e-commerce_302.jpg"/>
 </a>
 </div>
 <div class="rbt-card-body">
 <div class="rbt-card-top">
 <div class="rbt-review">
 <span class="rating-count"><i class="feather-book"></i> 4 Years</span>
 </div>
 </div>
 <h4 class="rbt-card-title"><a href="https://www.mul.edu.pk/en/program/bs-e-commerce">BS E-Commerce</a></h4>
 <div class="rbt-card-bottom">
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-e-commerce"> Find Out More <i class="feather-arrow-right"></i></a>
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>
 </div>
 </div>
 </div>
 </div>,
 <div class="maso-item cat--3 col-lg-4 mb--40">
 <div class="rbt-card variation-01 rbt-hover">
 <div class="rbt-card-img">
 <a href="https://www.mul.edu.pk/en/program/bs-in-digital-media-communication">
 <img alt="BS in Digital Media Communication" src="https://www.mul.edu.pk/images/programs/bs-in-digital-media-communication_311.jpg"/>
 </a>
 </div>
 <div class="rbt-card-body">
 <div class="rbt-card-top">
 <div class="rbt-review">
 <span class="rating-count"><i class="feather-book"></i> 4 Years</span>
 </div>
 </div>
 <h4 class="rbt-card-title"><a href="https://www.mul.edu.pk/en/program/bs-in-digital-media-communication">BS in Digital Media Communication</a></h4>
 <div class="rbt-card-bottom">
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-in-digital-media-communication"> Find Out More <i class="feather-arrow-right"></i></a>
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>
 </div>
 </div>
 </div>
 </div>,
 <div class="maso-item cat--3 col-lg-4 mb--40">
 <div class="rbt-card variation-01 rbt-hover">
 <div class="rbt-card-img">
 <a href="https://www.mul.edu.pk/en/program/bs-in-multimedia-arts-animation">
 <img alt="BS in Multimedia Arts- Animation" src="https://www.mul.edu.pk/images/programs/bs-in-multimedia-arts_312.jpg"/>
 </a>
 </div>
 <div class="rbt-card-body">
 <div class="rbt-card-top">
 <div class="rbt-review">
 <span class="rating-count"><i class="feather-book"></i> 4 Years</span>
 </div>
 </div>
 <h4 class="rbt-card-title"><a href="https://www.mul.edu.pk/en/program/bs-in-multimedia-arts-animation">BS in Multimedia Arts- Animation</a></h4>
 <div class="rbt-card-bottom">
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-in-multimedia-arts-animation"> Find Out More <i class="feather-arrow-right"></i></a>
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>
 </div>
 </div>
 </div>
 </div>,
 <div class="maso-item cat--3 col-lg-4 mb--40">
 <div class="rbt-card variation-01 rbt-hover">
 <div class="rbt-card-img">
 <a href="https://www.mul.edu.pk/en/program/bachelor-of-science-in-financial-technology">
 <img alt="Bachelor of Science in Financial Technology" src="https://www.mul.edu.pk/images/programs/bachelor-of-science-in-financial-technology_338.jpg"/>
 </a>
 </div>
 <div class="rbt-card-body">
 <div class="rbt-card-top">
 <div class="rbt-review">
 <span class="rating-count"><i class="feather-book"></i> 4 Years</span>
 </div>
 </div>
 <h4 class="rbt-card-title"><a href="https://www.mul.edu.pk/en/program/bachelor-of-science-in-financial-technology">Bachelor of Science in Financial Technology</a></h4>
 <div class="rbt-card-bottom">
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bachelor-of-science-in-financial-technology"> Find Out More <i class="feather-arrow-right"></i></a>
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>
 </div>
 </div>
 </div>
 </div>,
 <div class="maso-item cat--3 col-lg-4 mb--40">
 <div class="rbt-card variation-01 rbt-hover">
 <div class="rbt-card-img">
 <a href="https://www.mul.edu.pk/en/program/bs-economics-and-data-science">
 <img alt="BS Economics and Data Science" src="https://www.mul.edu.pk/images/programs/bs-economics-and-data-science_353.jpg"/>
 </a>
 </div>
 <div class="rbt-card-body">
 <div class="rbt-card-top">
 <div class="rbt-review">
 <span class="rating-count"><i class="feather-book"></i> 4 Years</span>
 </div>
 </div>
 <h4 class="rbt-card-title"><a href="https://www.mul.edu.pk/en/program/bs-economics-and-data-science">BS Economics and Data Science</a></h4>
 <div class="rbt-card-bottom">
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-economics-and-data-science"> Find Out More <i class="feather-arrow-right"></i></a>
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>
 </div>
 </div>
 </div>
 </div>,
 <div class="maso-item cat--3 col-lg-4 mb--40">
 <div class="rbt-card variation-01 rbt-hover">
 <div class="rbt-card-img">
 <a href="https://www.mul.edu.pk/en/program/bs-statistics-data-science">
 <img alt="BS Statistics &amp; Data Science" src="https://www.mul.edu.pk/images/programs/bs-statistics-data-science_358.jpg"/>
 </a>
 </div>
 <div class="rbt-card-body">
 <div class="rbt-card-top">
 <div class="rbt-review">
 <span class="rating-count"><i class="feather-book"></i> 4 Years</span>
 </div>
 </div>
 <h4 class="rbt-card-title"><a href="https://www.mul.edu.pk/en/program/bs-statistics-data-science">BS Statistics &amp; Data Science</a></h4>
 <div class="rbt-card-bottom">
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-statistics-data-science"> Find Out More <i class="feather-arrow-right"></i></a>
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>
 </div>
 </div>
 </div>
 </div>,
 <div class="maso-item cat--3 col-lg-4 mb--40">
 <div class="rbt-card variation-01 rbt-hover">
 <div class="rbt-card-img">
 <a href="https://www.mul.edu.pk/en/program/bs-computational-plant-sciences">
 <img alt="BS Computational Plant Sciences" src="https://www.mul.edu.pk/images/programs/bs-computational-plant-sciences_357.jpg"/>
 </a>
 </div>
 <div class="rbt-card-body">
 <div class="rbt-card-top">
 <div class="rbt-review">
 <span class="rating-count"><i class="feather-book"></i> 4 Years</span>
 </div>
 </div>
 <h4 class="rbt-card-title"><a href="https://www.mul.edu.pk/en/program/bs-computational-plant-sciences">BS Computational Plant Sciences</a></h4>
 <div class="rbt-card-bottom">
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-computational-plant-sciences"> Find Out More <i class="feather-arrow-right"></i></a>
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>
 </div>
 </div>
 </div>
 </div>,
 <div class="maso-item cat--3 col-lg-4 mb--40">
 <div class="rbt-card variation-01 rbt-hover">
 <div class="rbt-card-img">
 <a href="https://www.mul.edu.pk/en/program/bs-chemistry-industrial-entrepreneurship">
 <img alt="BS Chemistry &amp;  Industrial Entrepreneurship" src="https://www.mul.edu.pk/images/programs/bs-chemistry-industrial-entrepreneurship_356.jpg"/>
 </a>
 </div>
 <div class="rbt-card-body">
 <div class="rbt-card-top">
 <div class="rbt-review">
 <span class="rating-count"><i class="feather-book"></i> 4 Years</span>
 </div>
 </div>
 <h4 class="rbt-card-title"><a href="https://www.mul.edu.pk/en/program/bs-chemistry-industrial-entrepreneurship">BS Chemistry &amp;  Industrial Entrepreneurship</a></h4>
 <div class="rbt-card-bottom">
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-chemistry-industrial-entrepreneurship"> Find Out More <i class="feather-arrow-right"></i></a>
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>
 </div>
 </div>
 </div>
 </div>,
 <div class="maso-item cat--3 col-lg-4 mb--40">
 <div class="rbt-card variation-01 rbt-hover">
 <div class="rbt-card-img">
 <a href="https://www.mul.edu.pk/en/program/bs-information-system-technology-management">
 <img alt="BS Information System &amp; Technology Management" src="https://www.mul.edu.pk/images/programs/bs-information-system-technology-management_361.jpg"/>
 </a>
 </div>
 <div class="rbt-card-body">
 <div class="rbt-card-top">
 <div class="rbt-review">
 <span class="rating-count"><i class="feather-book"></i> 4 Years</span>
 </div>
 </div>
 <h4 class="rbt-card-title"><a href="https://www.mul.edu.pk/en/program/bs-information-system-technology-management">BS Information System &amp; Technology Management</a></h4>
 <div class="rbt-card-bottom">
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-information-system-technology-management"> Find Out More <i class="feather-arrow-right"></i></a>
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>
 </div>
 </div>
 </div>
 </div>,
 <div class="maso-item cat--3 col-lg-4 mb--40">
 <div class="rbt-card variation-01 rbt-hover">
 <div class="rbt-card-img">
 <a href="https://www.mul.edu.pk/en/program/bs-zoology-and-entomology">
 <img alt=" BS Zoology and Entomology" src="https://www.mul.edu.pk/images/programs/bs-zoology-and-entomology_362.jpg"/>
 </a>
 </div>
 <div class="rbt-card-body">
 <div class="rbt-card-top">
 <div class="rbt-review">
 <span class="rating-count"><i class="feather-book"></i> 4 Years</span>
 </div>
 </div>
 <h4 class="rbt-card-title"><a href="https://www.mul.edu.pk/en/program/bs-zoology-and-entomology"> BS Zoology and Entomology</a></h4>
 <div class="rbt-card-bottom">
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-zoology-and-entomology"> Find Out More <i class="feather-arrow-right"></i></a>
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>
 </div>
 </div>
 </div>
 </div>,
 <div class="maso-item cat--3 col-lg-4 mb--40">
 <div class="rbt-card variation-01 rbt-hover">
 <div class="rbt-card-img">
 <a href="https://www.mul.edu.pk/en/program/bs-islamic-banking-financial-technology">
 <img alt="BS Islamic Banking &amp;  Financial Technology" src="https://www.mul.edu.pk/images/programs/bs-islamic-banking-financial-technology_366.jpg"/>
 </a>
 </div>
 <div class="rbt-card-body">
 <div class="rbt-card-top">
 <div class="rbt-review">
 <span class="rating-count"><i class="feather-book"></i> 4 Years</span>
 </div>
 </div>
 <h4 class="rbt-card-title"><a href="https://www.mul.edu.pk/en/program/bs-islamic-banking-financial-technology">BS Islamic Banking &amp;  Financial Technology</a></h4>
 <div class="rbt-card-bottom">
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-islamic-banking-financial-technology"> Find Out More <i class="feather-arrow-right"></i></a>
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>
 </div>
 </div>
 </div>
 </div>,
 <div class="maso-item cat--3 col-lg-4 mb--40">
 <div class="rbt-card variation-01 rbt-hover">
 <div class="rbt-card-img">
 <a href="https://www.mul.edu.pk/en/program/bs-information-management">
 <img alt="BS Information Management" src="https://www.mul.edu.pk/images/programs/bs-information-management_365.jpg"/>
 </a>
 </div>
 <div class="rbt-card-body">
 <div class="rbt-card-top">
 <div class="rbt-review">
 <span class="rating-count"><i class="feather-book"></i> 4 Years</span>
 </div>
 </div>
 <h4 class="rbt-card-title"><a href="https://www.mul.edu.pk/en/program/bs-information-management">BS Information Management</a></h4>
 <div class="rbt-card-bottom">
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-information-management"> Find Out More <i class="feather-arrow-right"></i></a>
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>
 </div>
 </div>
 </div>
 </div>,
 <div class="maso-item cat--3 col-lg-4 mb--40">
 <div class="rbt-card variation-01 rbt-hover">
 <div class="rbt-card-img">
 <a href="https://www.mul.edu.pk/en/program/bs-mathematics-data-science">
 <img alt="BS Mathematics &amp; Data Science" src="https://www.mul.edu.pk/images/programs/bs-mathematics-data-science_367.jpg"/>
 </a>
 </div>
 <div class="rbt-card-body">
 <div class="rbt-card-top">
 <div class="rbt-review">
 <span class="rating-count"><i class="feather-book"></i> 4 Years</span>
 </div>
 </div>
 <h4 class="rbt-card-title"><a href="https://www.mul.edu.pk/en/program/bs-mathematics-data-science">BS Mathematics &amp; Data Science</a></h4>
 <div class="rbt-card-bottom">
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-mathematics-data-science"> Find Out More <i class="feather-arrow-right"></i></a>
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>
 </div>
 </div>
 </div>
 </div>,
 <div class="maso-item cat--3 col-lg-4 mb--40">
 <div class="rbt-card variation-01 rbt-hover">
 <div class="rbt-card-img">
 <a href="https://www.mul.edu.pk/en/program/bs-defense-and-strategic-studies">
 <img alt="BS Defense and Strategic Studies" src="https://www.mul.edu.pk/images/programs/bs-defense-and-strategic-studies_371.jpg"/>
 </a>
 </div>
 <div class="rbt-card-body">
 <div class="rbt-card-top">
 <div class="rbt-review">
 <span class="rating-count"><i class="feather-book"></i> 4 Years</span>
 </div>
 </div>
 <h4 class="rbt-card-title"><a href="https://www.mul.edu.pk/en/program/bs-defense-and-strategic-studies">BS Defense and Strategic Studies</a></h4>
 <div class="rbt-card-bottom">
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-defense-and-strategic-studies"> Find Out More <i class="feather-arrow-right"></i></a>
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>
 </div>
 </div>
 </div>
 </div>,
 <div class="maso-item cat--3 col-lg-4 mb--40">
 <div class="rbt-card variation-01 rbt-hover">
 <div class="rbt-card-img">
 <a href="https://www.mul.edu.pk/en/program/bachelor-of-laws-llb-4-years">
 <img alt="Bachelor of Laws (LLB) 4 years" src="https://www.mul.edu.pk/images/programs/bachelor-of-laws-llb-4-years_491.jpg"/>
 </a>
 </div>
 <div class="rbt-card-body">
 <div class="rbt-card-top">
 <div class="rbt-review">
 <span class="rating-count"><i class="feather-book"></i> 4 Years</span>
 </div>
 </div>
 <h4 class="rbt-card-title"><a href="https://www.mul.edu.pk/en/program/bachelor-of-laws-llb-4-years">Bachelor of Laws (LLB) 4 years</a></h4>
 <div class="rbt-card-bottom">
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bachelor-of-laws-llb-4-years"> Find Out More <i class="feather-arrow-right"></i></a>
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>
 </div>
 </div>
 </div>
 </div>,
 <div class="maso-item cat--3 col-lg-4 mb--40">
 <div class="rbt-card variation-01 rbt-hover">
 <div class="rbt-card-img">
 <a href="https://www.mul.edu.pk/en/program/bs-business-analytics">
 <img alt="BS Business Analytics" src="https://www.mul.edu.pk/images/programs/bs-business-analytics_492.jpg"/>
 </a>
 </div>
 <div class="rbt-card-body">
 <div class="rbt-card-top">
 <div class="rbt-review">
 <span class="rating-count"><i class="feather-book"></i> 4 Years</span>
 </div>
 </div>
 <h4 class="rbt-card-title"><a href="https://www.mul.edu.pk/en/program/bs-business-analytics">BS Business Analytics</a></h4>
 <div class="rbt-card-bottom">
 <a class="rbt-btn-link left-icon" href="https://www.mul.edu.pk/en/program/bs-business-analytics"> Find Out More <i class="feather-arrow-right"></i></a>
 <a class="rbt-btn-link left-icon" href="https://admission.mul.edu.pk/" target="_blank"> Apply Now <i class="feather-arrow-right"></i></a>
 </div>
 </div>
 </div>
 </div>,
 <div class="maso-item cat--3 col-lg-4 mb--40">
 <div class="rbt-card variation-01 rbt-hover">
 <div class="rbt-card-img">
 <a href="https://www.mul.edu.pk/en/program/bs-psychology">
 <img alt="BS Psychology" src="https://www.mul.edu.pk/images/programs/bs-psychology_507.jpg"/>
 </a>
 </div>
 <div class="rbt-card-body">
 <div class="rbt-card-top">
 <div class="rbt-review">
 <span class="rating-count"><i class="feather-book"></i> 4 years</span>
 </div>
 </div>

In [71]:
main[0]

<div class="rbt-card-img">
<a href="https://www.mul.edu.pk/en/program/bs-human-nutrition-and-dietetics">
<img alt="BS Human Nutrition and Dietetics" src="https://www.mul.edu.pk/images/programs/bs-human-nutrition-and-dietetics_245.jpg"/>
</a>
</div>

In [44]:
web = soup.find_all("div", class_="maso-item")

In [58]:
name = []

for i in web:
    course_name = i.find('a').find('img')['alt']
    name.append(course_name)

print(name)

['BS Human Nutrition and Dietetics', 'BS Criminology and Forensic Sciences', 'BS Digital Marketing', 'BS E-Commerce', 'BS in Digital Media Communication', 'BS in Multimedia Arts- Animation', 'Bachelor of Science in Financial Technology', 'BS Economics and Data Science', 'BS Statistics & Data Science', 'BS Computational Plant Sciences', 'BS Chemistry &  Industrial Entrepreneurship', 'BS Information System & Technology Management', ' BS Zoology and Entomology', 'BS Islamic Banking &  Financial Technology', 'BS Information Management', 'BS Mathematics & Data Science', 'BS Defense and Strategic Studies', 'Bachelor of Laws (LLB) 4 years', 'BS Business Analytics', 'BS Psychology', 'BS Aesthetics and Cosmetology', 'BS Computer Science', 'Doctor of Pharmacy', 'BS Information Technology', 'BS Software Engineering', 'BS Artificial Intelligence', 'BS Cyber Security', 'BBA', 'BS Education', 'BS Biotechnology', 'BS Data Science', 'BS English', 'BS Political Science', 'BS International Relations', 'BS Medical Laboratory Technology', 'BS Food Science & Technology', 'BS Economics', 'BS Economics and Financial Technology', 'BS Islamic Banking & Finance', 'B.Com (4 Year)', 'BS Accounting and Finance', 'BS Sociology', 'B.Sc. Chemical Engineering', 'B.Sc. Electrical Engineering', 'BS Biochemistry', 'BS Peace and Conflict Studies']

In [57]:
len(name)

46

In [61]:
df = pd.DataFrame({'course_name': name})
df.tail()

                      course_name
41                   BS Sociology
42     B.Sc. Chemical Engineering
43   B.Sc. Electrical Engineering
44                BS Biochemistry
45  BS Peace and Conflict Studies

In [67]:
links = []

for i in web:
    course_link = i.find('a')['href']
    links.append(course_link)

# print(links)

In [65]:
df = pd.DataFrame({"Course_Links": links})

In [66]:
df

                                         Course_Links
0   https://www.mul.edu.pk/en/program/bs-human-nut...
1   https://www.mul.edu.pk/en/program/bs-criminolo...
2   https://www.mul.edu.pk/en/program/bs-digital-m...
3     https://www.mul.edu.pk/en/program/bs-e-commerce
4   https://www.mul.edu.pk/en/program/bs-in-digita...
5   https://www.mul.edu.pk/en/program/bs-in-multim...
6   https://www.mul.edu.pk/en/program/bachelor-of-...
7   https://www.mul.edu.pk/en/program/bs-economics...
8   https://www.mul.edu.pk/en/program/bs-statistic...
9   https://www.mul.edu.pk/en/program/bs-computati...
10  https://www.mul.edu.pk/en/program/bs-chemistry...
11  https://www.mul.edu.pk/en/program/bs-informati...
12  https://www.mul.edu.pk/en/program/bs-zoology-a...
13  https://www.mul.edu.pk/en/program/bs-islamic-b...
14  https://www.mul.edu.pk/en/program/bs-informati...
15  https://www.mul.edu.pk/en/program/bs-mathemati...
16  https://www.mul.edu.pk/en/program/bs-defense-a...
17  https://www.mul.edu.pk/en/program/bachelor-of-...
18  https://www.mul.edu.pk/en/program/bs-business-...
19    https://www.mul.edu.pk/en/program/bs-psychology
20  https://www.mul.edu.pk/en/program/bs-aesthetic...
21  https://www.mul.edu.pk/en/program/bs-computer-...
22  https://www.mul.edu.pk/en/program/doctor-of-ph...
23  https://www.mul.edu.pk/en/program/bs-informati...
24  https://www.mul.edu.pk/en/program/bs-software-...
25  https://www.mul.edu.pk/en/program/bs-artificia...
26  https://www.mul.edu.pk/en/program/bs-cyber-sec...
27              https://www.mul.edu.pk/en/program/bba
28     https://www.mul.edu.pk/en/program/bs-education
29  https://www.mul.edu.pk/en/program/bs-biotechno...
30  https://www.mul.edu.pk/en/program/bs-data-science
31       https://www.mul.edu.pk/en/program/bs-english
32  https://www.mul.edu.pk/en/program/bs-political...
33  https://www.mul.edu.pk/en/program/bs-internati...
34  https://www.mul.edu.pk/en/program/bs-medical-l...
35  https://www.mul.edu.pk/en/program/bs-food-scie...
36     https://www.mul.edu.pk/en/program/bs-economics
37  https://www.mul.edu.pk/en/program/bs-economics...
38  https://www.mul.edu.pk/en/program/bs-islamic-b...
39      https://www.mul.edu.pk/en/program/bcom-4-year
40  https://www.mul.edu.pk/en/program/bs-accountin...
41     https://www.mul.edu.pk/en/program/bs-sociology
42  https://www.mul.edu.pk/en/program/bsc-chemical...
43  https://www.mul.edu.pk/en/program/bsc-electric...
44  https://www.mul.edu.pk/en/program/bs-biochemistry
45  https://www.mul.edu.pk/en/program/bs-peace-and...