# Fetching Data using Web Scraping

In [10]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [11]:
requests.get("https://www.vertexnetworking.co.uk")

In [12]:
webpage = requests.get("https://www.vertexnetworking.co.uk").text

In [13]:
webpage

'<!DOCTYPE html>\n<html lang="en">\n<meta http-equiv="content-type" content="text/html;charset=UTF-8"/>\n<head>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">\n    <title>Vertex Networking - Your Trusted Source for Quality Computer Hardware, Servers & PC Components</title>\n    <meta name="keywords" content="Shop Server and PC Components Online | Top Computer Hardware Store" />\n    <meta name="description" content="Vertax Networking is a leading computer hardware store offering top-quality server and PC components. Shop online for the latest innovations in technology and exceptional customer service.">\n    <meta name="author" content="Vertex Networking">\n    <meta name="csrf-token" content="u9gnsBn5Lwls42mvPzLU5xonhg4QE8uWuXEXATb7">\n    <link rel="apple-touch-icon" sizes="180x180" href="https://www.vertexnetworking.co.uk/frontend/favicon_io/apple-touch-icon.png">\n    <link rel="icon" type="image/png" sizes="32x32" href="https://www.vertexnetworking.co.uk/frontend/favicon_io/favicon-32x32.png">\n    <link rel="icon" type="image/png" sizes="16x16" href="https://www.vertexnetworking.co.uk/frontend/favicon_io/favicon-16x16.png">\n    <link rel="manifest" href="https://www.vertexnetworking.co.uk/frontend/favicon_io/site.webmanifest">\n    <!-- Favicon -->\n    \n    <!-- Preload Font -->\n    <link rel="preload" href="https://www.vertexnetworking.co.uk/frontend/fonts/riode115b.ttf?5gap68" as="font" type="font/woff2" crossorigin="anonymous">\n    <link rel="preload" href="https://www.vertexnetworking.co.uk/frontend/vendor/fontawesome-free/webfonts/fa-solid-900.woff2" as="font" type="font/woff2" crossorigin="anonymous">\n    <link rel="preload" href="https://www.vertexnetworking.co.uk/frontend/vendor/fontawesome-free/webfonts/fa-brands-400.woff2" as="font" type="font/woff2" crossorigin="anonymous">\n    \n    <link rel="stylesheet" type="text/css" href="https://www.vertexnetworking.co.uk/frontend/vendor/fontawesome-free/css/all.min.css">\n    <link rel="stylesheet" type="text/css" href="https://www.vertexnetworking.co.uk/frontend/vendor/animate/animate.min.css">\n    <!-- Plugins CSS File -->\n    \n    <link rel="stylesheet" type="text/css" href="https://www.vertexnetworking.co.uk/frontend/vendor/owl-carousel/owl.carousel.min.css">\n    \n    <!-- Main CSS File -->\n    <link rel="stylesheet" type="text/css" href="https://www.vertexnetworking.co.uk/frontend/css/demo6.min.css">\n    <link rel="stylesheet" type="text/css" href="https://www.vertexnetworking.co.uk/frontend/css/style.min.css">\n\n    <style>\n        .text-justify\n        {\n            text-align: justify;\n        }\n        .product-media {\n            display: flex;\n            justify-content: center;\n            align-items: center;\n            /* width: 280px; */\n            height: 315px !important; /* Adjust to your preferred size */\n            overflow: hidden; /* Ensures content outside the bounds is clipped */\n            position: relative;\n        }\n\n        .product-image {\n            width: 100% !important;\n            height: 100% !important;\n            object-fit: cover; /* Ensures the image fits within the container while maintaining aspect ratio */\n            object-position: center; /* Centers the image within the container */\n        }\n        .text-16\n        {\n            font-size: 16px !important;\n        }\n        .suggestion-box-mbl {\n            position: absolute;\n            left: 0;\n            background-color: #fff;\n            /* border: 1px solid #ccc; */\n            border-top: none;\n            border-radius: 0 0 4px 4px;\n            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\n            max-height: 400px;\n            overflow-y: auto;\n            padding: 0;\n            margin: 0;\n            list-style-type: none;\n            z-index: 1000;\n            width: 100%;\n        }\n\n        .search-div input.form-control\n        {\n            padding: 0 5rem 0 1.55rem;\n            border-radius: 5px;\n            border: 2px solid;\n            border-top-color: currentcolor;\n            border-right-color: currentcolor;\n            border-bottom-color: currentcolor;\n            border-left-color: currentcolor;\n            border-color: #44b3e9;\n            font-family: inherit;\n            background-color: #fff;\n            color: #999;\n        }\n\n        /* Show the div up to 767px */\n        @media (max-width: 767px) {\n            .search-div {\n                display: block;\n                padding: 10px;\n            }\n            .product-media\n            {\n                height: 135px !important;\n            }\n        }\n\n        /* Hide the div after 767px */\n        @media (min-width: 768px) {\n            .search-div {\n                display: none; /* Hide the div */\n            }\n        }\n    </style>\n</head>\n\n<body class="home">\n    <div class="page-wrapper">\n\n        <style>\r\n    .search-container {\r\n        position: relative;\r\n        width: 300px;\r\n    }\r\n\r\n    .search-box {\r\n        width: 100%;\r\n        padding: 10px;\r\n        border: 1px solid #ccc;\r\n        border-radius: 4px;\r\n        font-size: 16px;\r\n    }\r\n\r\n    .suggestion-box {\r\n        position: absolute;\r\n        top: 100%;\r\n        left: 0;\r\n        right: 0;\r\n        background-color: #fff;\r\n        /* border: 1px solid #ccc; */\r\n        border-top: none;\r\n        border-radius: 0 0 4px 4px;\r\n        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n        max-height: 200px;\r\n        overflow-y: auto;\r\n        padding: 0;\r\n        margin: 0;\r\n        list-style-type: none;\r\n        z-index: 1000;\r\n    }\r\n\r\n    .suggestion-item {\r\n        display: block;\r\n        padding: 10px;\r\n        color: #333;\r\n        text-decoration: none;\r\n        font-size: 16px;\r\n    }\r\n\r\n    .suggestion-item:hover {\r\n        background-color: #f1f1f1;\r\n    }\r\n\r\n    .no-suggestions {\r\n        padding: 10px;\r\n        color: #777;\r\n        font-style: italic;\r\n    }\r\n</style>\r\n\r\n\r\n\r\n<h1 class="d-none">Vertex Networking</h1>\r\n        <header class="header">\r\n            <div class="header-top" style="background-color: #f5f5f5">\r\n                <div class="container">\r\n                    <div class="header-left">\r\n                        <p class="welcome-msg">Welcome to Vertex Networking!</p>\r\n                    </div>\r\n                    <div class="header-right">\r\n\r\n                        <!-- End DropDown Menu -->\r\n                        <a href="https://www.vertexnetworking.co.uk/contact-us" class="contact d-lg-show" style="font-size: 14px;color: black;"><i class="d-icon-map"></i>Contact Us</a>\r\n                        \r\n                                                                        <a href="https://www.vertexnetworking.co.uk/login" class="link-to-tab d-md-show" style="font-size: 14px;color: black;"><i class="d-icon-user"></i>&nbsp;&nbsp;Login</a>\r\n                                            </div>\r\n                </div>\r\n            </div>\r\n            <!-- End HeaderTop -->\r\n            <div class="header-middle sticky-header fix-top sticky-content">\r\n                <div class="container">\r\n                    <div class="header-left">\r\n                        <a href="#" class="mobile-menu-toggle">\r\n                            <i class="d-icon-bars2"></i>\r\n                        </a>\r\n                        <a href="https://www.vertexnetworking.co.uk" class="logo">\r\n                            <img src="https://www.vertexnetworking.co.uk/frontend/images/vertex-networking-logo.png" alt="logo" />\r\n                        </a>\r\n                        <!-- End Logo -->\r\n\r\n                        <div class="header-search hs-simple">\r\n                            <form action="#" class="input-wrapper">\r\n                                <input type="text" class="form-control search-box" name="search" autocomplete="off" placeholder="Search..." oninput="fetchSuggestions(this.value)" required />\r\n                                <div class="suggestion-box" id="suggestionBox"></div>\r\n                                \r\n                            </form>\r\n                        </div>\r\n                        <!-- End Header Search -->\r\n                    </div>\r\n                    <div class="header-right">\r\n                        <a href="tel:+447367498493" class="icon-box icon-box-side">\r\n                            <div class="icon-box-icon mr-0 mr-lg-2">\r\n                                <i class="d-icon-phone"></i>\r\n                            </div>\r\n                            <div class="icon-box-content d-lg-show">\r\n                                <h4 class="icon-box-title">Call Us Now:</h4>\r\n                                <p>+447367498493</p>\r\n                            </div>\r\n                        </a>\r\n\r\n                        <span class="divider"></span>\r\n                        \r\n                        <div class="dropdown cart-dropdown type2 off-canvas mr-0 mr-lg-2">\r\n                            <a href="https://www.vertexnetworking.co.uk/cart" class="label-block link">\r\n                                <div class="cart-label d-lg-show">\r\n                                    <span class="cart-name">Shopping Cart:</span>\r\n                                    <span class="cart-price">$ 0.00</span>\r\n                                </div>\r\n\r\n                                <i class="d-icon-bag"><span class="cart-count">0</span></i>\r\n                            </a>\r\n                        </div>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n\r\n            <div class="header-bottom d-lg-show">\r\n                <div class="container">\r\n                    <div class="header-left">\r\n                        <nav class="main-nav">\r\n                            <ul class="menu">\r\n\r\n                                <li class="active"><a href="https://www.vertexnetworking.co.uk">Home</a></li>\r\n\r\n                                \r\n\r\n                                \r\n                                                                    <li>\r\n                                        <a href="https://www.vertexnetworking.co.uk/category/1">Storage Device</a>\r\n                                                                                    <ul>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/1">Hard Drives</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/2">Solid State Drives</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/3">Storage Accessories</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/4">Hard Drive Enclosure</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/5">Controllers</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/6">Tape Drives</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/7">Tape Media</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/8">Tape Libraries &amp; Autoloaders</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/9">USB Flash Drives</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/10">Memory Cards</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/11">I/O Cards/Panel</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/12">Floppy Drives</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/13">Network Storage Devices</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/14">Host Bus Adapter</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/15">Host Channel Adapter</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/16">Optical Drives &amp; Burners</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/17">Optical Media</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/18">Storage Array</a></li>\r\n                                                                                            </ul>\r\n                                                                            </li>\r\n                                                                    <li>\r\n                                        <a href="https://www.vertexnetworking.co.uk/category/2">Memory</a>\r\n                                                                                    <ul>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/19">Server Memory</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/20">Desktop Memory</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/21">Laptop Memory</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/22">Printer Memory</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/23">Network Memory</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/24">Gaming Memory</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/25">Cache Memory</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/26">Flash Memory</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/27">Memory Boards</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/28">Memory Chips DRAM</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/29">RDRAM - Rambus Memory</a></li>\r\n                                                                                            </ul>\r\n                                                                            </li>\r\n                                                                    <li>\r\n                                        <a href="https://www.vertexnetworking.co.uk/category/3">Network &amp; Accessories</a>\r\n                                                                                    <ul>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/30">Management Controller Module</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/31">Wireless Networking</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/32">Network Switches</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/33">Routers</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/34">VoIP Gateways</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/35">Media Converter</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/36">Network Adapters</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/37">Network Accessories</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/38">Transceivers</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/39">Switch Module</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/40">Modems</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/41">Powerline Network Adapters</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/42">Power Over Ethernet Adapters</a></li>\r\n                                                                                                    <li><a href="https://www.vertexnetworking.co.uk/subcategory/43">Network Security &amp; Firewall Devices</a></li>\r\n                                                                                                

In [14]:
soup = BeautifulSoup(webpage, "lxml")

In [15]:
soup

<!DOCTYPE html>
<html lang="en">
<head><meta content="text/html;charset=utf-8" http-equiv="content-type"/>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0, minimum-scale=1.0" name="viewport"/>
<title>Vertex Networking - Your Trusted Source for Quality Computer Hardware, Servers &amp; PC Components</title>
<meta content="Shop Server and PC Components Online | Top Computer Hardware Store" name="keywords"/>
<meta content="Vertax Networking is a leading computer hardware store offering top-quality server and PC components. Shop online for the latest innovations in technology and exceptional customer service." name="description"/>
<meta content="Vertex Networking" name="author"/>
<meta content="u9gnsBn5Lwls42mvPzLU5xonhg4QE8uWuXEXATb7" name="csrf-token"/>
<link href="https://www.vertexnetworking.co.uk/frontend/favicon_io/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="https://www.vertexnetworking.co.uk/frontend/favicon_io/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="https://www.vertexnetworking.co.uk/frontend/favicon_io/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="https://www.vertexnetworking.co.uk/frontend/favicon_io/site.webmanifest" rel="manifest"/>
<!-- Favicon -->
<!-- Preload Font -->
<link as="font" crossorigin="anonymous" href="https://www.vertexnetworking.co.uk/frontend/fonts/riode115b.ttf?5gap68" rel="preload" type="font/woff2"/>
<link as="font" crossorigin="anonymous" href="https://www.vertexnetworking.co.uk/frontend/vendor/fontawesome-free/webfonts/fa-solid-900.woff2" rel="preload" type="font/woff2"/>
<link as="font" crossorigin="anonymous" href="https://www.vertexnetworking.co.uk/frontend/vendor/fontawesome-free/webfonts/fa-brands-400.woff2" rel="preload" type="font/woff2"/>
<link href="https://www.vertexnetworking.co.uk/frontend/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css"/>
<link href="https://www.vertexnetworking.co.uk/frontend/vendor/animate/animate.min.css" rel="stylesheet" type="text/css"/>
<!-- Plugins CSS File -->
<link href="https://www.vertexnetworking.co.uk/frontend/vendor/owl-carousel/owl.carousel.min.css" rel="stylesheet" type="text/css"/>
<!-- Main CSS File -->
<link href="https://www.vertexnetworking.co.uk/frontend/css/demo6.min.css" rel="stylesheet" type="text/css"/>
<link href="https://www.vertexnetworking.co.uk/frontend/css/style.min.css" rel="stylesheet" type="text/css"/>
<style>
        .text-justify
        {
            text-align: justify;
        }
        .product-media {
            display: flex;
            justify-content: center;
            align-items: center;
            /* width: 280px; */
            height: 315px !important; /* Adjust to your preferred size */
            overflow: hidden; /* Ensures content outside the bounds is clipped */
            position: relative;
        }

        .product-image {
            width: 100% !important;
            height: 100% !important;
            object-fit: cover; /* Ensures the image fits within the container while maintaining aspect ratio */
            object-position: center; /* Centers the image within the container */
        }
        .text-16
        {
            font-size: 16px !important;
        }
        .suggestion-box-mbl {
            position: absolute;
            left: 0;
            background-color: #fff;
            /* border: 1px solid #ccc; */
            border-top: none;
            border-radius: 0 0 4px 4px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            max-height: 400px;
            overflow-y: auto;
            padding: 0;
            margin: 0;
            list-style-type: none;
            z-index: 1000;
            width: 100%;
        }

        .search-div input.form-control
        {
            padding: 0 5rem 0 1.55rem;
            border-radius: 5px;
            border: 2px solid;
            border-top-color: currentcolor;
            border-right-color: currentcolor;
            border-bottom-color: currentcolor;
            border-left-color: currentcolor;
            border-color: #44b3e9;
            font-family: inherit;
            background-color: #fff;
            color: #999;
        }

        /* Show the div up to 767px */
        @media (max-width: 767px) {
            .search-div {
                display: block;
                padding: 10px;
            }
            .product-media
            {
                height: 135px !important;
            }
        }

        /* Hide the div after 767px */
        @media (min-width: 768px) {
            .search-div {
                display: none; /* Hide the div */
            }
        }
    </style>
</head><body class="home">
<div class="page-wrapper">
<style>
    .search-container {
        position: relative;
        width: 300px;
    }

    .search-box {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        font-size: 16px;
    }

    .suggestion-box {
        position: absolute;
        top: 100%;
        left: 0;
        right: 0;
        background-color: #fff;
        /* border: 1px solid #ccc; */
        border-top: none;
        border-radius: 0 0 4px 4px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        max-height: 200px;
        overflow-y: auto;
        padding: 0;
        margin: 0;
        list-style-type: none;
        z-index: 1000;
    }

    .suggestion-item {
        display: block;
        padding: 10px;
        color: #333;
        text-decoration: none;
        font-size: 16px;
    }

    .suggestion-item:hover {
        background-color: #f1f1f1;
    }

    .no-suggestions {
        padding: 10px;
        color: #777;
        font-style: italic;
    }
</style>
<h1 class="d-none">Vertex Networking</h1>
<header class="header">
<div class="header-top" style="background-color: #f5f5f5">
<div class="container">
<div class="header-left">
<p class="welcome-msg">Welcome to Vertex Networking!</p>
</div>
<div class="header-right">
<!-- End DropDown Menu -->
<a class="contact d-lg-show" href="https://www.vertexnetworking.co.uk/contact-us" style="font-size: 14px;color: black;"><i class="d-icon-map"></i>Contact Us</a>
<a class="link-to-tab d-md-show" href="https://www.vertexnetworking.co.uk/login" style="font-size: 14px;color: black;"><i class="d-icon-user"></i>  Login</a>
</div>
</div>
</div>
<!-- End HeaderTop -->
<div class="header-middle sticky-header fix-top sticky-content">
<div class="container">
<div class="header-left">
<a class="mobile-menu-toggle" href="#">
<i class="d-icon-bars2"></i>
</a>
<a class="logo" href="https://www.vertexnetworking.co.uk">
<img alt="logo" src="https://www.vertexnetworking.co.uk/frontend/images/vertex-networking-logo.png"/>
</a>
<!-- End Logo -->
<div class="header-search hs-simple">
<form action="#" class="input-wrapper">
<input autocomplete="off" class="form-control search-box" name="search" oninput="fetchSuggestions(this.value)" placeholder="Search..." required="" type="text"/>
<div class="suggestion-box" id="suggestionBox"></div>
</form>
</div>
<!-- End Header Search -->
</div>
<div class="header-right">
<a class="icon-box icon-box-side" href="tel:+447367498493">
<div class="icon-box-icon mr-0 mr-lg-2">
<i class="d-icon-phone"></i>
</div>
<div class="icon-box-content d-lg-show">
<h4 class="icon-box-title">Call Us Now:</h4>
<p>+447367498493</p>
</div>
</a>
<span class="divider"></span>
<div class="dropdown cart-dropdown type2 off-canvas mr-0 mr-lg-2">
<a class="label-block link" href="https://www.vertexnetworking.co.uk/cart">
<div class="cart-label d-lg-show">
<span class="cart-name">Shopping Cart:</span>
<span class="cart-price">$ 0.00</span>
</div>
<i class="d-icon-bag"><span class="cart-count">0</span></i>
</a>
</div>
</div>
</div>
</div>
<div class="header-bottom d-lg-show">
<div class="container">
<div class="header-left">
<nav class="main-nav">
<ul class="menu">
<li class="active"><a href="https://www.vertexnetworking.co.uk">Home</a></li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/1">Storage Device</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/1">Hard Drives</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/2">Solid State Drives</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/3">Storage Accessories</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/4">Hard Drive Enclosure</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/5">Controllers</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/6">Tape Drives</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/7">Tape Media</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/8">Tape Libraries &amp; Autoloaders</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/9">USB Flash Drives</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/10">Memory Cards</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/11">I/O Cards/Panel</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/12">Floppy Drives</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/13">Network Storage Devices</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/14">Host Bus Adapter</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/15">Host Channel Adapter</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/16">Optical Drives &amp; Burners</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/17">Optical Media</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/18">Storage Array</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/2">Memory</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/19">Server Memory</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/20">Desktop Memory</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/21">Laptop Memory</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/22">Printer Memory</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/23">Network Memory</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/24">Gaming Memory</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/25">Cache Memory</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/26">Flash Memory</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/27">Memory Boards</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/28">Memory Chips DRAM</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/29">RDRAM - Rambus Memory</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/3">Network &amp; Accessories</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/30">Management Controller Module</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/31">Wireless Networking</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/32">Network Switches</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/33">Routers</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/34">VoIP Gateways</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/35">Media Converter</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/36">Network Adapters</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/37">Network Accessories</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/38">Transceivers</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/39">Switch Module</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/40">Modems</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/41">Powerline Network Adapters</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/42">Power Over Ethernet Adapters</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/43">Network Security &amp; Firewall Devices</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/44">Terminal Servers</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/45">IP Phones</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/46">Print Servers</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/4">PC &amp; Servers</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/47">Laptop PC</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/48">Laptop Accessories</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/49">Workstation Systems</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/50">Workstation Accessories</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/51">Servers</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/52">Server Accessories</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/53">Desktops</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/54">Desktop Accessories</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/55">Tablet PC</a></li>
</ul>
</li>
<li class="submenu">
<a href="#">Other Categories</a>
<ul>
<li>
<a href="https://www.vertexnetworking.co.uk/category/6">Motherboards</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/59">Desktop Motherboards</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/60">Server Motherboards</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/61">Laptop Motherboards</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/7">Printers &amp; Scanners</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/62">Printers</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/63">Printer Accessories</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/64">Printer Cartridges</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/65">Scanner Faxes &amp; Copiers</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/8">Power Equipment</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/66">Power Supplies</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/67">Power Adapters &amp; Chargers</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/68">UPS</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/69">PDUs</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/70">Surge Suppressors</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/71">Power Bank</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/72">Batteries</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/73">Power Accessories</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/9">Processors</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/74">Server Processors</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/75">Desktop Processors</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/76">Laptop Processors</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/77">Processor Boards</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/78">VRM</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/11">Audio Components</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/84">Headphone &amp; Headsets</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/85">Microphones</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/86">Sound Cards</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/87">Speakers</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/12">Input Devices</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/88">KVM Switches</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/89">Keyboards</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/90">Mouse</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/91">Keyboards</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/92">Input Device Accessories</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/14">Monitors</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/99">LCD/LED Monitors</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/100">CRT Monitors</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/101">Laptop Replacement Screen</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/102">Monitor Accessories</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/15">System Cooling Parts</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/103">Heatsink</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/104">CPU Fans</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/105">CPU Fans / Heatsinks</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/106">Thermal Compund / Grease</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/107">Fan Tray</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/16">Cables</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/108">Network Cables</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/109">Audio &amp; Video Cables</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/110">KVM Cables</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/111">Storage &amp; Data Transfer Cables</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/112">System &amp; Power Cables</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/17">Cameras</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/113">Surveillance Cameras</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/114">Webcams</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/115">Digital Cameras</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/116">Camera Parts &amp; Accessories</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/13">More Categories</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/97">Computer Accessories</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/98">ICs &amp; Micro Chips</a></li>
</ul>
</li>
</ul>
</li>
</ul>
</nav>
</div>
</div>
</div>
</header>
<main class="main">
<section class="search-div">
<div class="container">
<form action="#" class="input-wrapper">
<input autocomplete="off" class="form-control search-box" name="search" oninput="fetchSuggestionsMbl(this.value)" placeholder="Search..." required="" type="text"/>
<div class="suggestion-box-mbl" id="suggestionBoxMbl"></div>
</form>
</div>
</section>
<div class="page-content">
<style>
    .gradient-bg {
        background: linear-gradient(to right, #a6f0ff, #b5a2ff);
        padding: 30px;
    }
    .gradient-bg img {
        max-width: 100%;
        height: auto;
    }
    .w-80 {
        width: 80%;
    }

    .w-20 {
        width: 20%;
    }
</style>
<div class="container mt-4">
<div class="row g-4">
<div class="col-lg-8 col-md-12 d-flex">
<div class="d-flex align-items-center justify-content-between w-100 p-3">
<img alt="Headset" class="img-fluid" src="https://www.vertexnetworking.co.uk/frontend/images/home-banner-1st.png"/>
</div>
</div>

In [16]:
soup.prettify

<bound method Tag.prettify of <!DOCTYPE html>
<html lang="en">
<head><meta content="text/html;charset=utf-8" http-equiv="content-type"/>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0, minimum-scale=1.0" name="viewport"/>
<title>Vertex Networking - Your Trusted Source for Quality Computer Hardware, Servers &amp; PC Components</title>
<meta content="Shop Server and PC Components Online | Top Computer Hardware Store" name="keywords"/>
<meta content="Vertax Networking is a leading computer hardware store offering top-quality server and PC components. Shop online for the latest innovations in technology and exceptional customer service." name="description"/>
<meta content="Vertex Networking" name="author"/>
<meta content="u9gnsBn5Lwls42mvPzLU5xonhg4QE8uWuXEXATb7" name="csrf-token"/>
<link href="https://www.vertexnetworking.co.uk/frontend/favicon_io/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="https://www.vertexnetworking.co.uk/frontend/favicon_io/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="https://www.vertexnetworking.co.uk/frontend/favicon_io/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="https://www.vertexnetworking.co.uk/frontend/favicon_io/site.webmanifest" rel="manifest"/>
<!-- Favicon -->
<!-- Preload Font -->
<link as="font" crossorigin="anonymous" href="https://www.vertexnetworking.co.uk/frontend/fonts/riode115b.ttf?5gap68" rel="preload" type="font/woff2"/>
<link as="font" crossorigin="anonymous" href="https://www.vertexnetworking.co.uk/frontend/vendor/fontawesome-free/webfonts/fa-solid-900.woff2" rel="preload" type="font/woff2"/>
<link as="font" crossorigin="anonymous" href="https://www.vertexnetworking.co.uk/frontend/vendor/fontawesome-free/webfonts/fa-brands-400.woff2" rel="preload" type="font/woff2"/>
<link href="https://www.vertexnetworking.co.uk/frontend/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css"/>
<link href="https://www.vertexnetworking.co.uk/frontend/vendor/animate/animate.min.css" rel="stylesheet" type="text/css"/>
<!-- Plugins CSS File -->
<link href="https://www.vertexnetworking.co.uk/frontend/vendor/owl-carousel/owl.carousel.min.css" rel="stylesheet" type="text/css"/>
<!-- Main CSS File -->
<link href="https://www.vertexnetworking.co.uk/frontend/css/demo6.min.css" rel="stylesheet" type="text/css"/>
<link href="https://www.vertexnetworking.co.uk/frontend/css/style.min.css" rel="stylesheet" type="text/css"/>
<style>
        .text-justify
        {
            text-align: justify;
        }
        .product-media {
            display: flex;
            justify-content: center;
            align-items: center;
            /* width: 280px; */
            height: 315px !important; /* Adjust to your preferred size */
            overflow: hidden; /* Ensures content outside the bounds is clipped */
            position: relative;
        }

        .product-image {
            width: 100% !important;
            height: 100% !important;
            object-fit: cover; /* Ensures the image fits within the container while maintaining aspect ratio */
            object-position: center; /* Centers the image within the container */
        }
        .text-16
        {
            font-size: 16px !important;
        }
        .suggestion-box-mbl {
            position: absolute;
            left: 0;
            background-color: #fff;
            /* border: 1px solid #ccc; */
            border-top: none;
            border-radius: 0 0 4px 4px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            max-height: 400px;
            overflow-y: auto;
            padding: 0;
            margin: 0;
            list-style-type: none;
            z-index: 1000;
            width: 100%;
        }

        .search-div input.form-control
        {
            padding: 0 5rem 0 1.55rem;
            border-radius: 5px;
            border: 2px solid;
            border-top-color: currentcolor;
            border-right-color: currentcolor;
            border-bottom-color: currentcolor;
            border-left-color: currentcolor;
            border-color: #44b3e9;
            font-family: inherit;
            background-color: #fff;
            color: #999;
        }

        /* Show the div up to 767px */
        @media (max-width: 767px) {
            .search-div {
                display: block;
                padding: 10px;
            }
            .product-media
            {
                height: 135px !important;
            }
        }

        /* Hide the div after 767px */
        @media (min-width: 768px) {
            .search-div {
                display: none; /* Hide the div */
            }
        }
    </style>
</head><body class="home">
<div class="page-wrapper">
<style>
    .search-container {
        position: relative;
        width: 300px;
    }

    .search-box {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        font-size: 16px;
    }

    .suggestion-box {
        position: absolute;
        top: 100%;
        left: 0;
        right: 0;
        background-color: #fff;
        /* border: 1px solid #ccc; */
        border-top: none;
        border-radius: 0 0 4px 4px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        max-height: 200px;
        overflow-y: auto;
        padding: 0;
        margin: 0;
        list-style-type: none;
        z-index: 1000;
    }

    .suggestion-item {
        display: block;
        padding: 10px;
        color: #333;
        text-decoration: none;
        font-size: 16px;
    }

    .suggestion-item:hover {
        background-color: #f1f1f1;
    }

    .no-suggestions {
        padding: 10px;
        color: #777;
        font-style: italic;
    }
</style>
<h1 class="d-none">Vertex Networking</h1>
<header class="header">
<div class="header-top" style="background-color: #f5f5f5">
<div class="container">
<div class="header-left">
<p class="welcome-msg">Welcome to Vertex Networking!</p>
</div>
<div class="header-right">
<!-- End DropDown Menu -->
<a class="contact d-lg-show" href="https://www.vertexnetworking.co.uk/contact-us" style="font-size: 14px;color: black;"><i class="d-icon-map"></i>Contact Us</a>
<a class="link-to-tab d-md-show" href="https://www.vertexnetworking.co.uk/login" style="font-size: 14px;color: black;"><i class="d-icon-user"></i>  Login</a>
</div>
</div>
</div>
<!-- End HeaderTop -->
<div class="header-middle sticky-header fix-top sticky-content">
<div class="container">
<div class="header-left">
<a class="mobile-menu-toggle" href="#">
<i class="d-icon-bars2"></i>
</a>
<a class="logo" href="https://www.vertexnetworking.co.uk">
<img alt="logo" src="https://www.vertexnetworking.co.uk/frontend/images/vertex-networking-logo.png"/>
</a>
<!-- End Logo -->
<div class="header-search hs-simple">
<form action="#" class="input-wrapper">
<input autocomplete="off" class="form-control search-box" name="search" oninput="fetchSuggestions(this.value)" placeholder="Search..." required="" type="text"/>
<div class="suggestion-box" id="suggestionBox"></div>
</form>
</div>
<!-- End Header Search -->
</div>
<div class="header-right">
<a class="icon-box icon-box-side" href="tel:+447367498493">
<div class="icon-box-icon mr-0 mr-lg-2">
<i class="d-icon-phone"></i>
</div>
<div class="icon-box-content d-lg-show">
<h4 class="icon-box-title">Call Us Now:</h4>
<p>+447367498493</p>
</div>
</a>
<span class="divider"></span>
<div class="dropdown cart-dropdown type2 off-canvas mr-0 mr-lg-2">
<a class="label-block link" href="https://www.vertexnetworking.co.uk/cart">
<div class="cart-label d-lg-show">
<span class="cart-name">Shopping Cart:</span>
<span class="cart-price">$ 0.00</span>
</div>
<i class="d-icon-bag"><span class="cart-count">0</span></i>
</a>
</div>
</div>
</div>
</div>
<div class="header-bottom d-lg-show">
<div class="container">
<div class="header-left">
<nav class="main-nav">
<ul class="menu">
<li class="active"><a href="https://www.vertexnetworking.co.uk">Home</a></li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/1">Storage Device</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/1">Hard Drives</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/2">Solid State Drives</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/3">Storage Accessories</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/4">Hard Drive Enclosure</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/5">Controllers</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/6">Tape Drives</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/7">Tape Media</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/8">Tape Libraries &amp; Autoloaders</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/9">USB Flash Drives</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/10">Memory Cards</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/11">I/O Cards/Panel</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/12">Floppy Drives</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/13">Network Storage Devices</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/14">Host Bus Adapter</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/15">Host Channel Adapter</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/16">Optical Drives &amp; Burners</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/17">Optical Media</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/18">Storage Array</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/2">Memory</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/19">Server Memory</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/20">Desktop Memory</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/21">Laptop Memory</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/22">Printer Memory</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/23">Network Memory</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/24">Gaming Memory</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/25">Cache Memory</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/26">Flash Memory</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/27">Memory Boards</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/28">Memory Chips DRAM</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/29">RDRAM - Rambus Memory</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/3">Network &amp; Accessories</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/30">Management Controller Module</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/31">Wireless Networking</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/32">Network Switches</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/33">Routers</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/34">VoIP Gateways</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/35">Media Converter</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/36">Network Adapters</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/37">Network Accessories</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/38">Transceivers</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/39">Switch Module</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/40">Modems</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/41">Powerline Network Adapters</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/42">Power Over Ethernet Adapters</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/43">Network Security &amp; Firewall Devices</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/44">Terminal Servers</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/45">IP Phones</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/46">Print Servers</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/4">PC &amp; Servers</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/47">Laptop PC</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/48">Laptop Accessories</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/49">Workstation Systems</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/50">Workstation Accessories</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/51">Servers</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/52">Server Accessories</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/53">Desktops</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/54">Desktop Accessories</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/55">Tablet PC</a></li>
</ul>
</li>
<li class="submenu">
<a href="#">Other Categories</a>
<ul>
<li>
<a href="https://www.vertexnetworking.co.uk/category/6">Motherboards</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/59">Desktop Motherboards</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/60">Server Motherboards</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/61">Laptop Motherboards</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/7">Printers &amp; Scanners</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/62">Printers</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/63">Printer Accessories</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/64">Printer Cartridges</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/65">Scanner Faxes &amp; Copiers</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/8">Power Equipment</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/66">Power Supplies</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/67">Power Adapters &amp; Chargers</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/68">UPS</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/69">PDUs</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/70">Surge Suppressors</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/71">Power Bank</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/72">Batteries</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/73">Power Accessories</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/9">Processors</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/74">Server Processors</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/75">Desktop Processors</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/76">Laptop Processors</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/77">Processor Boards</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/78">VRM</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/11">Audio Components</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/84">Headphone &amp; Headsets</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/85">Microphones</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/86">Sound Cards</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/87">Speakers</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/12">Input Devices</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/88">KVM Switches</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/89">Keyboards</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/90">Mouse</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/91">Keyboards</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/92">Input Device Accessories</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/14">Monitors</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/99">LCD/LED Monitors</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/100">CRT Monitors</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/101">Laptop Replacement Screen</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/102">Monitor Accessories</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/15">System Cooling Parts</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/103">Heatsink</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/104">CPU Fans</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/105">CPU Fans / Heatsinks</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/106">Thermal Compund / Grease</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/107">Fan Tray</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/16">Cables</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/108">Network Cables</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/109">Audio &amp; Video Cables</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/110">KVM Cables</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/111">Storage &amp; Data Transfer Cables</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/112">System &amp; Power Cables</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/17">Cameras</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/113">Surveillance Cameras</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/114">Webcams</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/115">Digital Cameras</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/116">Camera Parts &amp; Accessories</a></li>
</ul>
</li>
<li>
<a href="https://www.vertexnetworking.co.uk/category/13">More Categories</a>
<ul>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/97">Computer Accessories</a></li>
<li><a href="https://www.vertexnetworking.co.uk/subcategory/98">ICs &amp; Micro Chips</a></li>
</ul>
</li>
</ul>
</li>
</ul>
</nav>
</div>
</div>
</div>
</header>
<main class="main">
<section class="search-div">
<div class="container">
<form action="#" class="input-wrapper">
<input autocomplete="off" class="form-control search-box" name="search" oninput="fetchSuggestionsMbl(this.value)" placeholder="Search..." required="" type="text"/>
<div class="suggestion-box-mbl" id="suggestionBoxMbl"></div>
</form>
</div>
</section>
<div class="page-content">
<style>
    .gradient-bg {
        background: linear-gradient(to right, #a6f0ff, #b5a2ff);
        padding: 30px;
    }
    .gradient-bg img {
        max-width: 100%;
        height: auto;
    }
    .w-80 {
        width: 80%;
    }

    .w-20 {
        width: 20%;
    }
</style>
<div class="container mt-4">
<div class="row g-4">
<div class="col-lg-8 col-md-12 d-flex">
<div class="d-flex align-items-center justify-content-between w-100 p-3">
<img alt="Headset" class="img-fluid" src="https://www.vertexnetworking.co.uk/frontend/images/home-banner-1st.png"/>
</div>
</div>

In [18]:
soup.find_all("h2")[0].text

'Vertex Networking'

In [19]:
len(soup.find_all("h2"))

4

In [20]:
soup.find_all("a")

[<a class="contact d-lg-show" href="https://www.vertexnetworking.co.uk/contact-us" style="font-size: 14px;color: black;"><i class="d-icon-map"></i>Contact Us</a>,
 <a class="link-to-tab d-md-show" href="https://www.vertexnetworking.co.uk/login" style="font-size: 14px;color: black;"><i class="d-icon-user"></i>  Login</a>,
 <a class="mobile-menu-toggle" href="#">
 <i class="d-icon-bars2"></i>
 </a>,
 <a class="logo" href="https://www.vertexnetworking.co.uk">
 <img alt="logo" src="https://www.vertexnetworking.co.uk/frontend/images/vertex-networking-logo.png"/>
 </a>,
 <a class="icon-box icon-box-side" href="tel:+447367498493">
 <div class="icon-box-icon mr-0 mr-lg-2">
 <i class="d-icon-phone"></i>
 </div>
 <div class="icon-box-content d-lg-show">
 <h4 class="icon-box-title">Call Us Now:</h4>
 <p>+447367498493</p>
 </div>
 </a>,
 <a class="label-block link" href="https://www.vertexnetworking.co.uk/cart">
 <div class="cart-label d-lg-show">
 <span class="cart-name">Shopping Cart:</span>
 <span class="cart-price">$ 0.00</span>
 </div>
 <i class="d-icon-bag"><span class="cart-count">0</span></i>
 </a>,
 <a href="https://www.vertexnetworking.co.uk">Home</a>,
 <a href="https://www.vertexnetworking.co.uk/category/1">Storage Device</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/1">Hard Drives</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/2">Solid State Drives</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/3">Storage Accessories</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/4">Hard Drive Enclosure</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/5">Controllers</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/6">Tape Drives</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/7">Tape Media</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/8">Tape Libraries &amp; Autoloaders</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/9">USB Flash Drives</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/10">Memory Cards</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/11">I/O Cards/Panel</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/12">Floppy Drives</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/13">Network Storage Devices</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/14">Host Bus Adapter</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/15">Host Channel Adapter</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/16">Optical Drives &amp; Burners</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/17">Optical Media</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/18">Storage Array</a>,
 <a href="https://www.vertexnetworking.co.uk/category/2">Memory</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/19">Server Memory</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/20">Desktop Memory</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/21">Laptop Memory</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/22">Printer Memory</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/23">Network Memory</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/24">Gaming Memory</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/25">Cache Memory</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/26">Flash Memory</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/27">Memory Boards</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/28">Memory Chips DRAM</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/29">RDRAM - Rambus Memory</a>,
 <a href="https://www.vertexnetworking.co.uk/category/3">Network &amp; Accessories</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/30">Management Controller Module</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/31">Wireless Networking</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/32">Network Switches</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/33">Routers</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/34">VoIP Gateways</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/35">Media Converter</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/36">Network Adapters</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/37">Network Accessories</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/38">Transceivers</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/39">Switch Module</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/40">Modems</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/41">Powerline Network Adapters</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/42">Power Over Ethernet Adapters</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/43">Network Security &amp; Firewall Devices</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/44">Terminal Servers</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/45">IP Phones</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/46">Print Servers</a>,
 <a href="https://www.vertexnetworking.co.uk/category/4">PC &amp; Servers</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/47">Laptop PC</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/48">Laptop Accessories</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/49">Workstation Systems</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/50">Workstation Accessories</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/51">Servers</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/52">Server Accessories</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/53">Desktops</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/54">Desktop Accessories</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/55">Tablet PC</a>,
 <a href="#">Other Categories</a>,
 <a href="https://www.vertexnetworking.co.uk/category/6">Motherboards</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/59">Desktop Motherboards</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/60">Server Motherboards</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/61">Laptop Motherboards</a>,
 <a href="https://www.vertexnetworking.co.uk/category/7">Printers &amp; Scanners</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/62">Printers</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/63">Printer Accessories</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/64">Printer Cartridges</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/65">Scanner Faxes &amp; Copiers</a>,
 <a href="https://www.vertexnetworking.co.uk/category/8">Power Equipment</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/66">Power Supplies</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/67">Power Adapters &amp; Chargers</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/68">UPS</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/69">PDUs</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/70">Surge Suppressors</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/71">Power Bank</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/72">Batteries</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/73">Power Accessories</a>,
 <a href="https://www.vertexnetworking.co.uk/category/9">Processors</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/74">Server Processors</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/75">Desktop Processors</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/76">Laptop Processors</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/77">Processor Boards</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/78">VRM</a>,
 <a href="https://www.vertexnetworking.co.uk/category/11">Audio Components</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/84">Headphone &amp; Headsets</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/85">Microphones</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/86">Sound Cards</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/87">Speakers</a>,
 <a href="https://www.vertexnetworking.co.uk/category/12">Input Devices</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/88">KVM Switches</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/89">Keyboards</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/90">Mouse</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/91">Keyboards</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/92">Input Device Accessories</a>,
 <a href="https://www.vertexnetworking.co.uk/category/14">Monitors</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/99">LCD/LED Monitors</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/100">CRT Monitors</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/101">Laptop Replacement Screen</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/102">Monitor Accessories</a>,
 <a href="https://www.vertexnetworking.co.uk/category/15">System Cooling Parts</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/103">Heatsink</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/104">CPU Fans</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/105">CPU Fans / Heatsinks</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/106">Thermal Compund / Grease</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/107">Fan Tray</a>,
 <a href="https://www.vertexnetworking.co.uk/category/16">Cables</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/108">Network Cables</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/109">Audio &amp; Video Cables</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/110">KVM Cables</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/111">Storage &amp; Data Transfer Cables</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/112">System &amp; Power Cables</a>,
 <a href="https://www.vertexnetworking.co.uk/category/17">Cameras</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/113">Surveillance Cameras</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/114">Webcams</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/115">Digital Cameras</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/116">Camera Parts &amp; Accessories</a>,
 <a href="https://www.vertexnetworking.co.uk/category/13">More Categories</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/97">Computer Accessories</a>,
 <a href="https://www.vertexnetworking.co.uk/subcategory/98">ICs &amp; Micro Chips</a>,
 <a href="#">
 <figure class="category-media">
 <img alt="category" src="https://www.vertexnetworking.co.uk/storage/brand_images/1736074611-hp.webp" style="width: 128px !importatn;height:128px !importatn;"/>
 </figure>
 </a>,
 <a href="#">
 <figure class="category-media">
 <img alt="category" src="https://www.vertexnetworking.co.uk/storage/brand_images/1736074712-wd.webp" style="width: 128px !importatn;height:128px !importatn;"/>
 </figure>
 </a>,
 <a href="#">
 <figure class="category-media">
 <img alt="category" src="https://www.vertexnetworking.co.uk/storage/brand_images/1736074652-ibm.webp" style="width: 128px !importatn;height:128px !importatn;"/>
 </figure>
 </a>,
 <a href="#">
 <figure class="category-media">
 <img alt="category" src="https://www.vertexnetworking.co.uk/storage/brand_images/1736074664-toshiba.webp" style="width: 128px !importatn;height:128px !importatn;"/>
 </figure>
 </a>,
 <a href="#">
 <figure class="category-media">
 <img alt="category" src="https://www.vertexnetworking.co.uk/storage/brand_images/1736074688-lenovo.webp" style="width: 128px !importatn;height:128px !importatn;"/>
 </figure>
 </a>,
 <a href="#">
 <figure class="category-media">
 <img alt="category" src="https://www.vertexnetworking.co.uk/storage/brand_images/1736074631-cisco.webp" style="width: 128px !importatn;height:128px !importatn;"/>
 </figure>
 </a>,
 <a href="#">
 <figure class="category-media">
 <img alt="category" src="https://www.vertexnetworking.co.uk/storage/brand_images/1736074640-fujitsu.webp" style="width: 128px !importatn;height:128px !importatn;"/>
 </figure>
 </a>,
 <a href="#">
 <figure class="category-media">
 <img alt="category" src="https://www.vertexnetworking.co.uk/storage/brand_images/1736074804-samsung.webp" style="width: 128px !importatn;height:128px !importatn;"/>
 </figure>
 </a>,
 <a href="#">
 <figure class="category-media">
 <img alt="category" src="https://www.vertexnetworking.co.uk/storage/brand_images/1736074675-kingston.webp" style="width: 128px !importatn;height:128px !importatn;"/>
 </figure>
 </a>,
 <a href="#">
 <figure class="category-media">
 <img alt="category" src="https://www.vertexnetworking.co.uk/storage/brand_images/1736074721-ubiquiti.webp" style="width: 128px !importatn;height:128px !importatn;"/>
 </figure>
 </a>,
 <a href="#">
 <figure class="category-media">
 <img alt="category" src="https://www.vertexnetworking.co.uk/storage/brand_images/1736074703-tp-link.webp" style="width: 128px !importatn;height:128px !importatn;"/>
 </figure>
 </a>,
 <a href="#">
 <figure class="category-media">
 <img alt="category" src="https://www.vertexnetworking.co.uk/storage/brand_images/1736074794-seagate.webp" style="width: 128px !importatn;height:128px !importatn;"/>
 </figure>
 </a>,
 <a class="nav-filter active font-weight-semi-bold" data-filter="*" href="#">All</a>,
 <a class="nav-filter font-weight-semi-bold" data-filter=".1" href="#">Storage Device</a>,
 <a class="nav-filter font-weight-semi-bold" data-filter=".2" href="#">Memory</a>,
 <a class="nav-filter font-weight-semi-bold" data-filter=".3" href="#">Network &amp; Accessories</a>,
 <a class="nav-filter font-weight-semi-bold" data-filter=".4" href="#">PC &amp; Servers</a>,
 <a class="nav-filter font-weight-semi-bold" data-filter=".5" href="#">Softwares</a>,
 <a href="https://www.vertexnetworking.co.uk/product/st900mp0006-seagate-enterprise-performance-15k-hdd-900gb-15000rpm-sas-12gb-s-256mb-cache-3-5-inch-hard-drive.html">
 <img alt="product" class="product-image" src="https://www.vertexnetworking.co.uk/storage/product_images/6778ffe75731c_ST900MP0006-o.webp"/>
 </a>,
 <a class="btn-product-icon" href="https://www.vertexnetworking.co.uk/product/st900mp0006-seagate-enterprise-performance-15k-hdd-900gb-15000rpm-sas-12gb-s-256mb-cache-3-5-inch-hard-drive.html" title="Add to cart"><i class="d-icon-bag"></i></a>,
 <a class="btn-product-icon" href="https://www.vertexnetworking.co.uk/product/st900mp0006-seagate-enterprise-performance-15k-hdd-900gb-15000rpm-sas-12gb-s-256mb-cache-3-5-inch-hard-drive.html" title="Add to wishlist"><i class="d-icon-heart"></i></a>,
 <a class="btn-product" href="https://www.vertexnetworking.co.uk/product/st900mp0006-seagate-enterprise-performance-15k-hdd-900gb-15000rpm-sas-12gb-s-256mb-cache-3-5-inch-hard-drive.html" title="Quick View">Quick View</a>,
 <a href="https://www.vertexnetworking.co.uk/category/1">Storage Device</a>,
 <a href="https://www.vertexnetworking.co.uk/product/st900mp0006-seagate-enterprise-performance-15k-hdd-900gb-15000rpm-sas-12gb-s-256mb-cache-3-5-inch-hard-drive.html">Seagate ST900MP0006 900GB 15000RPM SAS 12Gb/s 2.5-in Hard Drive</a>,
 <a class="rating-reviews" href="https://www.vertexnetworking.co.uk/product/st900mp0006-seagate-enterprise-performance-15k-hdd-900gb-15000rpm-sas-12gb-s-256mb-cache-3-5-inch-hard-drive.html">( 8 reviews )</a>,
 <a href="https://www.vertexnetworking.co.uk/product/fw4kg-dell-server-hard-drive.html">
 <img alt="product" class="product-image" src="https://www.vertexnetworking.co.uk/storage/product_images/6778ffe7cbeb8_FW4KG.webp"/>
 </a>,
 <a class="btn-product-icon" href="https://www.vertexnetworking.co.uk/product/fw4kg-dell-server-hard-drive.html" title="Add to cart"><i class="d-icon-bag"></i></a>,
 <a class="btn-product-icon" href="https://www.vertexnetworking.co.uk/product/fw4kg-dell-server-hard-drive.html" title="Add to wishlist"><i class="d-icon-heart"></i></a>,
 <a class="btn-product" href="https://www.vertexnetworking.co.uk/product/fw4kg-dell-server-hard-drive.html" title="Quick View">Quick View</a>,
 <a href="https://www.vertexnetworking.co.uk/category/1">Storage Device</a>,
 <a href="https://www.vertexnetworking.co.uk/product/fw4kg-dell-server-hard-drive.html">Dell FW4KG 4TB 7200RPM SAS 12Gb/s 3.5-inch Hard Drive</a>,
 <a class="rating-reviews" href="https://www.vertexnetworking.co.uk/product/fw4kg-dell-server-hard-drive.html">( 8 reviews )</a>,
 <a href="https://www.vertexnetworking.co.uk/product/870795-001-hp-enterprise-900gb-15000rpm-sas-12gb-s-2-5-inch-hard-drive.html">
 <img alt="product" class="product-image" src="https://www.vertexnetworking.co.uk/storage/product_images/6778ffe838db7_870795-001.webp"/>
 </a>,
 <a class="btn-product-icon" href="https://www.vertexnetworking.co.uk/product/870795-001-hp-enterprise-900gb-15000rpm-sas-12gb-s-2-5-inch-hard-drive.html" title="Add to cart"><i class="d-icon-bag"></i></a>,
 <a class="btn-product-icon" href="https://www.vertexnetworking.co.uk/product/870795-001-hp-enterprise-900gb-15000rpm-sas-12gb-s-2-5-inch-hard-drive.html" title="Add to wishlist"><i class="d-icon-heart"></i></a>,
 <a class="btn-product" href="https://www.vertexnetworking.co.uk/product/870795-001-hp-enterprise-900gb-15000rpm-sas-12gb-s-2-5-inch-hard-drive.html" title="Quick View">Quick View</a>,
 <a href="https://www.vertexnetworking.co.uk/category/1">Storage Device</a>,
 <a href="https://www.vertexnetworking.co.uk/product/870795-001-hp-enterprise-900gb-15000rpm-sas-12gb-s-2-5-inch-hard-drive.html">HPE 870795-001 900GB 15000RPM SAS 12Gb/s 2.5-in Hard Drive</a>,
 <a class="rating-reviews" href="https://www.vertexnetworking.co.uk/product/870795-001-hp-enterprise-900gb-15000rpm-sas-12gb-s-2-5-inch-hard-drive.html">( 8 reviews )</a>,
 <a href="https://www.vertexnetworking.co.uk/product/fxg2n-dell-server-hard-drive.html">
 <img alt="product" class="product-image" src="https://www.vertexnetworking.co.uk/storage/product_images/6778ffe8a770b_FXG2N.webp"/>
 </a>,
 <a class="btn-product-icon" href="https://www.vertexnetworking.co.uk/product/fxg2n-dell-server-hard-drive.html" title="Add to cart"><i class="d-icon-bag"></i></a>,
 <a class="btn-product-icon" href="https://www.vertexnetworking.co.uk/product/fxg2n-dell-server-hard-drive.html" title="Add to wishlist"><i class="d-icon-heart"></i></a>,
 <a class="btn-product" href="https://www.vertexnetworking.co.uk/product/fxg2n-dell-server-hard-drive.html" title="Quick View">Quick View</a>,
 <a href="https://www.vertexnetworking.co.uk/category/1">Storage Device</a>,
 <a href="https://www.vertexnetworking.co.uk/product/fxg2n-dell-server-hard-drive.html">Dell FXG2N 2TB 7200RPM SATA 6Gb/s 2.5-in Hard Drive</a>,
 <a class="rating-reviews" href="https://www.vertexnetworking.co.uk/product/fxg2n-dell-server-hard-drive.html">( 8 reviews )</a>,
 <a href="https://www.vertexnetworking.co.uk/product/870759-b21-hp-900gb-15000rpm-sas-12gb-s-2-5-inch-hard-drive.html">
 <img alt="product" class="product-image" src="https://www.vertexnetworking.co.uk/storage/product_images/6778ffe9194d4_870759-B21.webp"/>
 </a>,
 <a class="btn-product-icon" href="https://www.vertexnetworking.co.uk/product/870759-b21-hp-900gb-15000rpm-sas-12gb-s-2-5-inch-hard-drive.html" title="Add to cart"><i class="d-icon-bag"></i></a>,
 <a class="btn-product-icon" href="https://www.vertexnetworking.co.uk/product/870759-b21-hp-900gb-15000rpm-sas-12gb-s-2-5-inch-hard-drive.html" title="Add to wishlist"><i class="d-icon-heart"></i></a>,

In [21]:
for i in soup.find_all("a"):
    print(i.text.strip())

Contact Us
Login


Call Us Now:
+447367498493
Shopping Cart:
$ 0.00

0
Home
Storage Device
Hard Drives
Solid State Drives
Storage Accessories
Hard Drive Enclosure
Controllers
Tape Drives
Tape Media
Tape Libraries & Autoloaders
USB Flash Drives
Memory Cards
I/O Cards/Panel
Floppy Drives
Network Storage Devices
Host Bus Adapter
Host Channel Adapter
Optical Drives & Burners
Optical Media
Storage Array
Memory
Server Memory
Desktop Memory
Laptop Memory
Printer Memory
Network Memory
Gaming Memory
Cache Memory
Flash Memory
Memory Boards
Memory Chips DRAM
RDRAM - Rambus Memory
Network & Accessories
Management Controller Module
Wireless Networking
Network Switches
Routers
VoIP Gateways
Media Converter
Network Adapters
Network Accessories
Transceivers
Switch Module
Modems
Powerline Network Adapters
Power Over Ethernet Adapters
Network Security & Firewall Devices
Terminal Servers
IP Phones
Print Servers
PC & Servers
Laptop PC
Laptop Accessories
Workstation Systems
Workstation Accessories
Servers
Server Accessories
Desktops
Desktop Accessories
Tablet PC
Other Categories
Motherboards
Desktop Motherboards
Server Motherboards
Laptop Motherboards
Printers & Scanners
Printers
Printer Accessories
Printer Cartridges
Scanner Faxes & Copiers
Power Equipment
Power Supplies
Power Adapters & Chargers
UPS
PDUs
Surge Suppressors
Power Bank
Batteries
Power Accessories
Processors
Server Processors
Desktop Processors
Laptop Processors
Processor Boards
VRM
Audio Components
Headphone & Headsets
Microphones
Sound Cards
Speakers
Input Devices
KVM Switches
Keyboards
Mouse
Keyboards
Input Device Accessories
Monitors
LCD/LED Monitors
CRT Monitors
Laptop Replacement Screen
Monitor Accessories
System Cooling Parts
Heatsink
CPU Fans
CPU Fans / Heatsinks
Thermal Compund / Grease
Fan Tray
Cables
Network Cables
Audio & Video Cables
KVM Cables
Storage & Data Transfer Cables
System & Power Cables
Cameras
Surveillance Cameras
Webcams
Digital Cameras
Camera Parts & Accessories
More Categories
Computer Accessories
ICs & Micro Chips












All
Storage Device
Memory
Network & Accessories
PC & Servers
Softwares



Quick View
Storage Device
Seagate ST900MP0006 900GB 15000RPM SAS 12Gb/s 2.5-in Hard Drive
( 8 reviews )



Quick View
Storage Device
Dell FW4KG 4TB 7200RPM SAS 12Gb/s 3.5-inch Hard Drive
( 8 reviews )



Quick View
Storage Device
HPE 870795-001 900GB 15000RPM SAS 12Gb/s 2.5-in Hard Drive
( 8 reviews )



Quick View
Storage Device
Dell FXG2N 2TB 7200RPM SATA 6Gb/s 2.5-in Hard Drive
( 8 reviews )



Quick View
Storage Device
HPE 870759-B21 900GB 15000RPM SAS 12Gb/s 2.5-in Hard Drive
( 8 reviews )



Quick View
Storage Device
Dell KT3WC 1TB 7200RPM SATA 6Gb/s 2.5-in Hard Drive
( 8 reviews )



Quick View
Storage Device
HPE 867254-003 900GB 15000RPM SAS 12Gb/s 2.5-Inch Hard Drive
( 8 reviews )



Quick View
Storage Device
Dell KRM6X 4TB 7200RPM SAS 12Gb/s 3.5-inch Hard Drive
( 8 reviews )
Storage Device
Memory
Network & Accessories
PC & Servers
Softwares

Buy Now
Storage Device
Seagate ST900MP0006 900GB 15000RPM SAS 12Gb/s 2.5-in Hard Drive


Buy Now
Storage Device
Dell FW4KG 4TB 7200RPM SAS 12Gb/s 3.5-inch Hard Drive


Buy Now
Storage Device
HPE 870795-001 900GB 15000RPM SAS 12Gb/s 2.5-in Hard Drive


Buy Now
Storage Device
Dell FXG2N 2TB 7200RPM SATA 6Gb/s 2.5-in Hard Drive


Buy Now
Storage Device
HPE 870759-B21 900GB 15000RPM SAS 12Gb/s 2.5-in Hard Drive


Buy Now
Storage Device
Dell KT3WC 1TB 7200RPM SATA 6Gb/s 2.5-in Hard Drive


Buy Now
Storage Device
HPE 867254-003 900GB 15000RPM SAS 12Gb/s 2.5-Inch Hard Drive


Buy Now
Storage Device
Dell KRM6X 4TB 7200RPM SAS 12Gb/s 3.5-inch Hard Drive

Filter
Clean All
$0.00 - $50.00
$50.00 - $100.00
$100.00 - $200.00
$200.00+
Cinderella
Comedy
Rightcheck
SkillStar
SLS

+447367498493
orders@vertexnetworking.co.uk
17 Hat Tech Business Centre, Beaconsfield Court, Beaconsfield Road, Hatfield, AL10 8FF, United Kingdom
Mon - Sun / 9:00 AM - 8:00 PM
Home
About Us
FAQ's
Terms & Condition
Privacy Policy
Contact Us
Sign in
View Cart





Home
Storage Device
Hard Drives
Solid State Drives
Storage Accessories
Hard Drive Enclosure
Controllers
Tape Drives
Tape Media
Tape Libraries & Autoloaders
USB Flash Drives
Memory Cards
I/O Cards/Panel
Floppy Drives
Network Storage Devices
Host Bus Adapter
Host Channel Adapter
Optical Drives & Burners
Optical Media
Storage Array
Memory
Server Memory
Desktop Memory
Laptop Memory
Printer Memory
Network Memory
Gaming Memory
Cache Memory
Flash Memory
Memory Boards
Memory Chips DRAM
RDRAM - Rambus Memory
Network & Accessories
Management Controller Module
Wireless Networking
Network Switches
Routers
VoIP Gateways
Media Converter
Network Adapters
Network Accessories
Transceivers
Switch Module
Modems
Powerline Network Adapters
Power Over Ethernet Adapters
Network Security & Firewall Devices
Terminal Servers
IP Phones
Print Servers
PC & Servers
Laptop PC
Laptop Accessories
Workstation Systems
Workstation Accessories
Servers
Server Accessories
Desktops
Desktop Accessories
Tablet PC
Motherboards
Desktop Motherboards
Server Motherboards
Laptop Motherboards
Printers & Scanners
Printers
Printer Accessories
Printer Cartridges
Scanner Faxes & Copiers
Power Equipment
Power Supplies
Power Adapters & Chargers
UPS
PDUs
Surge Suppressors
Power Bank
Batteries
Power Accessories
Processors
Server Processors
Desktop Processors
Laptop Processors
Processor Boards
VRM
Audio Components
Headphone & Headsets
Microphones
Sound Cards
Speakers
Input Devices
KVM Switches
Keyboards
Mouse
Keyboards
Input Device Accessories
Monitors
LCD/LED Monitors
CRT Monitors
Laptop Replacement Screen
Monitor Accessories
System Cooling Parts
Heatsink
CPU Fans
CPU Fans / Heatsinks
Thermal Compund / Grease
Fan Tray
Cables
Network Cables
Audio & Video Cables
KVM Cables
Storage & Data Transfer Cables
System & Power Cables
Cameras
Surveillance Cameras
Webcams
Digital Cameras
Camera Parts & Accessories
More Categories
Computer Accessories
ICs & Micro Chips
About US
Contact US
Login
My Cart

In [22]:
main = soup.find_all('div', class_='rbt-card-img')

In [23]:
soup.find_all("div", class_="maso-item")

[]

In [24]:
main[0]

IndexError: list index out of range

In [44]:
web = soup.find_all("div", class_="maso-item")

In [58]:
name = []

for i in web:
    course_name = i.find('a').find('img')['alt']
    name.append(course_name)

print(name)

['BS Human Nutrition and Dietetics', 'BS Criminology and Forensic Sciences', 'BS Digital Marketing', 'BS E-Commerce', 'BS in Digital Media Communication', 'BS in Multimedia Arts- Animation', 'Bachelor of Science in Financial Technology', 'BS Economics and Data Science', 'BS Statistics & Data Science', 'BS Computational Plant Sciences', 'BS Chemistry &  Industrial Entrepreneurship', 'BS Information System & Technology Management', ' BS Zoology and Entomology', 'BS Islamic Banking &  Financial Technology', 'BS Information Management', 'BS Mathematics & Data Science', 'BS Defense and Strategic Studies', 'Bachelor of Laws (LLB) 4 years', 'BS Business Analytics', 'BS Psychology', 'BS Aesthetics and Cosmetology', 'BS Computer Science', 'Doctor of Pharmacy', 'BS Information Technology', 'BS Software Engineering', 'BS Artificial Intelligence', 'BS Cyber Security', 'BBA', 'BS Education', 'BS Biotechnology', 'BS Data Science', 'BS English', 'BS Political Science', 'BS International Relations', 'BS Medical Laboratory Technology', 'BS Food Science & Technology', 'BS Economics', 'BS Economics and Financial Technology', 'BS Islamic Banking & Finance', 'B.Com (4 Year)', 'BS Accounting and Finance', 'BS Sociology', 'B.Sc. Chemical Engineering', 'B.Sc. Electrical Engineering', 'BS Biochemistry', 'BS Peace and Conflict Studies']

In [57]:
len(name)

46

In [61]:
df = pd.DataFrame({'course_name': name})
df.tail()

                      course_name
41                   BS Sociology
42     B.Sc. Chemical Engineering
43   B.Sc. Electrical Engineering
44                BS Biochemistry
45  BS Peace and Conflict Studies

In [67]:
links = []

for i in web:
    course_link = i.find('a')['href']
    links.append(course_link)

# print(links)

In [65]:
df = pd.DataFrame({"Course_Links": links})

In [66]:
df

                                         Course_Links
0   https://www.mul.edu.pk/en/program/bs-human-nut...
1   https://www.mul.edu.pk/en/program/bs-criminolo...
2   https://www.mul.edu.pk/en/program/bs-digital-m...
3     https://www.mul.edu.pk/en/program/bs-e-commerce
4   https://www.mul.edu.pk/en/program/bs-in-digita...
5   https://www.mul.edu.pk/en/program/bs-in-multim...
6   https://www.mul.edu.pk/en/program/bachelor-of-...
7   https://www.mul.edu.pk/en/program/bs-economics...
8   https://www.mul.edu.pk/en/program/bs-statistic...
9   https://www.mul.edu.pk/en/program/bs-computati...
10  https://www.mul.edu.pk/en/program/bs-chemistry...
11  https://www.mul.edu.pk/en/program/bs-informati...
12  https://www.mul.edu.pk/en/program/bs-zoology-a...
13  https://www.mul.edu.pk/en/program/bs-islamic-b...
14  https://www.mul.edu.pk/en/program/bs-informati...
15  https://www.mul.edu.pk/en/program/bs-mathemati...
16  https://www.mul.edu.pk/en/program/bs-defense-a...
17  https://www.mul.edu.pk/en/program/bachelor-of-...
18  https://www.mul.edu.pk/en/program/bs-business-...
19    https://www.mul.edu.pk/en/program/bs-psychology
20  https://www.mul.edu.pk/en/program/bs-aesthetic...
21  https://www.mul.edu.pk/en/program/bs-computer-...
22  https://www.mul.edu.pk/en/program/doctor-of-ph...
23  https://www.mul.edu.pk/en/program/bs-informati...
24  https://www.mul.edu.pk/en/program/bs-software-...
25  https://www.mul.edu.pk/en/program/bs-artificia...
26  https://www.mul.edu.pk/en/program/bs-cyber-sec...
27              https://www.mul.edu.pk/en/program/bba
28     https://www.mul.edu.pk/en/program/bs-education
29  https://www.mul.edu.pk/en/program/bs-biotechno...
30  https://www.mul.edu.pk/en/program/bs-data-science
31       https://www.mul.edu.pk/en/program/bs-english
32  https://www.mul.edu.pk/en/program/bs-political...
33  https://www.mul.edu.pk/en/program/bs-internati...
34  https://www.mul.edu.pk/en/program/bs-medical-l...
35  https://www.mul.edu.pk/en/program/bs-food-scie...
36     https://www.mul.edu.pk/en/program/bs-economics
37  https://www.mul.edu.pk/en/program/bs-economics...
38  https://www.mul.edu.pk/en/program/bs-islamic-b...
39      https://www.mul.edu.pk/en/program/bcom-4-year
40  https://www.mul.edu.pk/en/program/bs-accountin...
41     https://www.mul.edu.pk/en/program/bs-sociology
42  https://www.mul.edu.pk/en/program/bsc-chemical...
43  https://www.mul.edu.pk/en/program/bsc-electric...
44  https://www.mul.edu.pk/en/program/bs-biochemistry
45  https://www.mul.edu.pk/en/program/bs-peace-and...