# Working with CSV files

## Data Gathering
1. CSV Files
2. JSON/SQL
3. Fetch data from an API
4. Data scraping from website (Web scraping)

## CSV (Comma Separated values) FILES
(80 - 90)% we are going to deal with csv data file

In [1]:
import pandas as pd

In [7]:
# Read from the local system
df = pd.read_csv("placement.csv")
df

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

In [4]:
# Read from the online server or resource
df = pd.read_csv("https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv")

In [5]:
df

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [10]:
# Start from specific row of the data

df = pd.read_csv("https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv", header = 1)

In [9]:
df

       Algeria         AFRICA
0       Angola         AFRICA
1        Benin         AFRICA
2     Botswana         AFRICA
3      Burkina         AFRICA
4      Burundi         AFRICA
..         ...            ...
188   Paraguay  SOUTH AMERICA
189       Peru  SOUTH AMERICA
190   Suriname  SOUTH AMERICA
191    Uruguay  SOUTH AMERICA
192  Venezuela  SOUTH AMERICA

[193 rows x 2 columns]

In [17]:
# Need specific columns

df = pd.read_csv("placement.csv", usecols =['cgpa','iq'])

In [18]:
df

    cgpa     iq
0    6.8  123.0
1    5.9  106.0
2    5.3  121.0
3    7.4  132.0
4    5.8  142.0
..   ...    ...
95   4.3  200.0
96   4.4   42.0
97   6.7  182.0
98   6.3  103.0
99   6.2  113.0

[100 rows x 2 columns]

In [19]:
# Squezee parameters

In [23]:
df = pd.read_csv("placement.csv", usecols=['cgpa']).squeeze()

In [24]:
df

0     6.8
1     5.9
2     5.3
3     7.4
4     5.8
     ...
95    4.3
96    4.4
97    6.7
98    6.3
99    6.2
Name: cgpa, Length: 100, dtype: float64

In [30]:
# Skip rows

df = pd.read_csv("placement.csv", usecols=['cgpa'], nrows=10)

In [32]:
df

   cgpa
0   6.8
1   5.9
2   5.3
3   7.4
4   5.8
5   7.1
6   5.7
7   5.0
8   6.1
9   5.1

In [45]:
# Skips bad lines or irregular values.

# df = pd.read_csv("placement.csv", usecols=['cgpa'], nrows=10, error_bad_lines=True)

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cgpa    100 non-null    float64
dtypes: float64(1)
memory usage: 932.0 bytes